### ISSUE TITLE
[Feature Request] Drag/Drop Image -> Upload To Cloud Provider

### ISSUE THREAD

**Issue by joemccann** [joemccann/dillinger#129]
As a Dilinger user, I want to be able to drag and drop an image into the editor and it provide me the resultant markdown for the image.

The image will need to be uploaded to a cloud provider somewhere.

**Comment by jvandemo** [comment]
+1 That would be an amazing feature!

**Comment by ZuBB** [comment]
If that will be ever done I suggesting dropbox as image storage

**Comment by blowsie** [comment]
This is one feature that is missing from Dillinger, Marxico has this feature, its really neat.

**Comment by joemccann** [comment]
Okay I added this in 3.10.0

Currently only support drag/drop images and you need Dropbox connected.  I will add support for Google Drive, and OneDrive soon enough.

**Comment by nikmd23** [comment]
Great feature, I'd love to see support for GitHub added as an upload target though. With this, Dillinger can replace Prose.io for me

**Comment by joemccann** [comment]
Does GitHub have an image upload API? Currently this works with Dropbox as
I'm not aware of an image upload API for Github

**Comment by nikmd23** [comment]
My assumption was that you'd use the same API as you do for the "Save To" feature. Could you upload the image file the same way you upload the .md file?

**Comment by joemccann** [comment]
Right, but the issue is when you upload an image (or save a markdown file)
you are in essence create a new commit.  So what we'd need to do is
"commit" the image (with or without a commit message) and then somehow get
the URL to the image to then be embedded.

`
https://raw.githubusercontent.com/username/projectname/branch/path/to/img.png`

Something like that.

In essence, we'd have to do this behind the scenes:

```sh
git add xxx.png
git commit -m 'add png file'
git remote add origin https://github.com/xxx.git
git push -u origin master
```

**Comment by nikmd23** [comment]
I'm personally okay with the extra commits to upload the file. That's what I'd have to do manually anyways, so Dillinger would just be saving me a bunch of time - and allow mostly non-technical users to contribute to docs without worrying about Git.

**Comment by joemccann** [comment]
good point!  Let's do it
