### ISSUE TITLE
Feature Request: Explorer-type listing to select files and open

### ISSUE THREAD

**Issue by enygma** [joemccann/dillinger#130]
It'd be nice if there was a way to view the list of files currently available to Dillinger (like on Dropbox) so they could be opened by double-clicking or something. Right now, if I want to edit a file I have to look up the name and put it in the "path" box.

Even an auto-complete would be a good first step (no need to create the nested list in the sidebar for that). Not sure if it's a feature or not, but you can put in a "path" as the name and have Dillinger write to a different directory that's not the root like: "/testing/foo/layers/This is a test" writes to "Dillinger/testing/foo/layers/This is a test.md".

**Comment by benjamin-albert** [comment]
The import features in version 3 allow you to list available files.

This issue has been inactive quite a while so I'm closing it.
