### ISSUE TITLE
[Feature Request]Auto scrolldown

### ISSUE THREAD

**Issue by skys215** [joemccann/dillinger#132]
Since I was writing a long md file, the preview area always shows from the top of the file.
But what i wanna see is where i edited just now.
So I think it's worth to auto scroll the preview area to where has been edited.

You can scroll to where the cursor was, or compare between the last render content and scroll to where has been modified.

Thxs,
Best regards

**Comment by dandv** [comment]
Not working as of now in Chrome.

Alternatives that work:
* StackEdit, albeit without [taking into consideration image height](https://github.com/benweet/stackedit/issues/777)
* Markable.in - but it always scrolls at the very bottom

**Comment by benweet** [comment]
@dandv StackEdit does take section height into consideration. A section in StackEdit is essentially text between headings.
So the workaround is to add a heading after your image and scroll down to it.

**Comment by dasJ** [comment]
With Firefox 31.6, I can't enable the option. Is this a Chrome-Only thing?

**Comment by dasJ** [comment]
Nope, doesn't work in Chrome either
