### ISSUE TITLE
[Bug Report] Title box malposition

### ISSUE THREAD

**Issue by skys215** [joemccann/dillinger#133]
![Title box malposition](http://i1275.photobucket.com/albums/y455/skys215/Github/dillinger_zpse0ea3e25.png)
I had this problem on TheWorld6.2.0.124(based on Chrome 31.0.1650.57)
I don't know why and when it happens, it drop once and quickly get back to the right position.
I'll comment this issue if it happens again.

Thx
Best regards

**Comment by benjamin-albert** [comment]
This issue has been inactive quite a while so I'm closing it.
