### ISSUE TITLE
JavaScript is executed inside editor

### ISSUE THREAD

**Issue by evancohen** [joemccann/dillinger#160]
There is no JavaScript filter in the markup. Any JavaScript that is entered into the editor is executed, for instance:
```
<script>alert(0)</script>
```

While it is not possible to hijack GitHub and DropBox sessions because they are HttpOnly, it's still something that should be looked at.

**Comment by benjamin-albert** [comment]
As of version 3.0 all HTML is escaped (which is being discussed in #325).  I'm closing this now.
