### ISSUE TITLE
No indication given as to where local files are stored

### ISSUE THREAD

**Issue by 2PMEnterprises** [joemccann/dillinger#199]
Choosing Local Files brings up the list of files created, but no idea where these are actually stored.  Windows 7, Firefox and Chrome. As the installation instructions say to create a set of folders, public/files/{}, I thought they might be there, but no.

**Comment by benjamin-albert** [comment]
Iv'e implemented drag and drop file import.  I also added the Import from -> File on disc menu item which allows choosing a file using the browsers file chooser.

It's now available on dillinger.io

For details see #521
