### ISSUE TITLE
Store on server not showing up as an option

### ISSUE THREAD

**Issue by 2PMEnterprises** [joemccann/dillinger#207]
edit: This is also based on the instructions that tell you to make new directories, and if not for the server to store copies, then what could it be because there's nothing in there.

Looking through the source I see a message is on the page to tell the user the file was saved on the server, so I assume this is supposed to be an option.
Running an instance on my desktop, browser connected to same.

**Comment by misterbisson** [comment]
This may be duplicated in https://github.com/joemccann/dillinger/issues/297, which now has additional information.

**Comment by benjamin-albert** [comment]
This issue has been inactive quite a while so I'm closing it.
