### ISSUE TITLE
GFM Not Rendering Images

### ISSUE THREAD

**Issue by joemccann** [joemccann/dillinger#210]
Something is definitely not right.  Since we added option to select editor, images aren't rendering.

+ @swang

![image](https://cloud.githubusercontent.com/assets/48234/3420840/b7e1ea26-fec6-11e3-8110-691b3e6d9e41.png)

**Comment by benjamin-albert** [comment]
Since version 3.0 all HTML is escaped in preview.

Let's continue this conversation in #325
