### ISSUE TITLE
Feature Request - Better & Easy to use UI

### ISSUE THREAD

**Issue by coding-idiot** [joemccann/dillinger#216]
1. Ability to expand both the panels
2. Ability to get the source-code of HTML
3. All missing pieces (compared to StackEdit) like -
   a. Auto-Sync with google-drive/dropbox

Just found that both Dillinger has the same issue (as StackEdit), create a new document & hit-save, it'll not create a new document in drive, instead it'll update the old one (loses content)! :(

Looks like I'll have to keep searching for collaborative, better syncing markdown editor that works with google-drive.

**Comment by PhiLhoSoft** [comment]
Don't forget people using your software are not necessarily coders, and even less necessarily JS coders...

**Comment by joemccann** [comment]
Thanks Phillippe, but I would also ask that you respect that this is free
software that no one is paying me or any of the contributors to host and
maintain. ☺️

If you'd like to hire me and pay me to add this feature please let me know!

**Comment by PhiLhoSoft** [comment]
I totally respect that, and totally understand free time isn't extensible (I know that by personal experience!).
That's just that your nice software is probably used by non-programmers (that's its purpose, no?) and your answer, which is totally valid for, eg., a JavaScript library used by JS programmers, isn't totally suited here.
That said, of course, anybody else can takes the proposed feature suggestion and implement them! 😄
