### ISSUE TITLE
Convert characters to HTML entities in "Show HTML" mode

### ISSUE THREAD

**Issue by TomLany** [joemccann/dillinger#217]
When you press Utilities > Show HTML, characters are not converted to HTML entities. To test this, I added the following sentence with fancy quotes to a document, and then viewed the HTML:

Let’s see what happens when I add these kinds of “fancy quotes” to my document.

Characters are correctly converted when you press Utliities > Export as HTML File.

**Comment by nfasulo** [comment]
This is still an issue whether you press Preview As or Export As > HTML (or Styled HTML).
