### ISSUE TITLE
When language specified is 'text', dillinger still tries to use syntax highlighting for code block

### ISSUE THREAD

**Issue by kkleidal** [joemccann/dillinger#218]
This is building off issue #203 and pull request #204 .  GitHub allows you to skip syntax highlighting for code blocks if you specify 'text' as the language.  For example:
\`\`\`text
some text in a block which isn't syntax highlighted
\`\`\`
but Dillinger still tries to use highlight.js to do syntax highlighting.

**Comment by CleanCut** [comment]
+1
