### ISSUE TITLE
Add option to delay updating the Markdown preview

### ISSUE THREAD

**Issue by daniellmb** [joemccann/dillinger#248]
![image](https://cloud.githubusercontent.com/assets/108018/4869680/bbece66e-6151-11e4-8f06-db019ded95d6.png)

This is especially important when working with large documents. I'm working with a 6,000+ word markdown file and it takes nearly **5 seconds to update the preview**. What's worse is that this is happening with [every single key up](https://github.com/joemccann/dillinger/blob/ba94052ae32869a8fba97a53fe16d7febe0b9edd/public/js/dillinger.js#L927) making the editor unusable. At the very least the function call should be [debounced](http://davidwalsh.name/javascript-debounce-function).

![image](https://cloud.githubusercontent.com/assets/108018/4869675/a022a5b8-6151-11e4-8c70-a28d80b41e89.png)

**Comment by owenallenaz** [comment]
Related: #283
