### ISSUE TITLE
Support for Taskpaper?

### ISSUE THREAD

**Issue by Ahbrown41** [joemccann/dillinger#250]
This is a great app, thanks for giving it to the world!  While I am a developer I am terrible at java script or I would add it myself..  Any chance you have considered adding support for task paper?  Any idea how I could even hack in support?  Tried adding it to "fileExts" in the dillinger.js file and that did not get me going yet.  Any ideas?

Thanks!

**Comment by benjamin-albert** [comment]
I agree Dillinger should stay focused on Markdown.

This feature request has been inactive quite a while so I'm closing it.
