### ISSUE TITLE
Import from Github not finding any branches

### ISSUE THREAD

**Issue by ryan-williams** [joemccann/dillinger#264]
I just created the public repo [hammerlab/yarn-logs-helpers](https://github.com/hammerlab/yarn-logs-helpers) and added a `README.md` that I'm trying to import into Dillinger. When I go to "Import From" > "Github" > "hammerlab" > "yarn-logs-helpers" I get an empty "Branches" picker:

![](http://f.cl.ly/items/460e2z3i191A0p1W0x2z/Screen%20Shot%202014-11-17%20at%204.37.07%20PM.png)

`hammerlab/yarn-logs-helpers` does have a `master` branch:

![](http://f.cl.ly/items/0d100X2G0b201a2V3x0I/Screen%20Shot%202014-11-19%20at%2011.53.23%20PM.png)

Other public and private repos under `hammerlab` seem to work fine for me (except for one private repo, `hammerlab/snippets`, that I created a couple of days ago and first filed this issue about before editing it to focus on the public repo, since that is presumably easier for people to investigate).

Anyone seen this or know what the issue could be?

**Comment by batandwa** [comment]
I have encountered this same problem. I think the issues here is that the owner of the branches request is wrong. It should be the organisation name. 

When I alter owner parameter I actually get object with the master (as the only) branch.

Now to set this up locally so I can perhaps find a solutions and submit a patch.

**Comment by D34D10CK** [comment]
Hi,
I'm having the exact same problem, does a workaround exists?

**Comment by stahl-c** [comment]
I'm having the same problem. Anything new on this front?

**Comment by snuggles08** [comment]
+1

**Comment by snuggles08** [comment]
It only does this for repos on organizations.

**Comment by locaterobin** [comment]
@batandwa were you able to fix this?

**Comment by rberger** [comment]
Anything new on this? Being able to edit Github docs is the killer feature for me. 
Thanks

**Comment by batandwa** [comment]
Fixed and working locally. Just submitted a pull request #510. This is the first time I write NodeJS code, so I hope I have messed anything up.
