### ISSUE TITLE
[feature request] please bring the "show html" option back

### ISSUE THREAD

**Issue by nodesiremonk** [joemccann/dillinger#277]
I remember there used to be a "Show HTML" option in the old version that I can quickly get all the html code by ctrl-a && ctrl-c.  

![image](https://cloud.githubusercontent.com/assets/1267069/5457438/459e0370-8510-11e4-8ff8-b14b86e45e86.png)

However, under the new version it seems the only way to do that is to export to html file first, then open the downloaded html file to retrieve the code.  

Is it possible to bring this feature back? Thanks!

**Comment by joemccann** [comment]
Yeah agreed.  Didn't realize it went away. @mrtnbroder thoughts?

**Comment by mrtnbroder** [comment]
I'm totally busy atm but adding it shouldn't be that hard.

instead of `html` you set it as `text` here I guess.

https://github.com/joemccann/dillinger/blob/master/public/js/components/preview.directive.js#L29-L32

**Comment by jay01684** [comment]
I hope that this feature can be back soon.
It's a **great** feature for users that use dillinger as a editor for some web platforms which have no built-in Markdown support!!
