### ISSUE TITLE
'angular-bootstrap' is not in the npm registry

### ISSUE THREAD

**Issue by suucc** [joemccann/dillinger#280]
npm http GET https://registry.npmjs.org/karma/-/karma-0.12.28.tgz
npm http 200 https://registry.npmjs.org/karma/-/karma-0.12.28.tgz
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'angular-bootstrap' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'Dillinger'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "-d"
npm ERR! cwd /home/suji/dillinger
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/suji/dillinger/npm-debug.log
npm ERR! not ok code 0

**Comment by spxis** [comment]
This does seem like a global issue - my installation failed as well on MacOSX.

**Comment by ZuBB** [comment]
@joemccann, could you please answer on my [question](https://github.com/joemccann/dillinger/issues/280#issuecomment-68060347)?

**Comment by joemccann** [comment]
So the issue is the version being referenced in the package.json?

**Comment by ZuBB** [comment]
yes, for some reason anyone who tries to setup a local copy of dillinger faces with this issue: package (its name and version) cant be find in npm repo.

ps: same thing people trying to say/resolve in #298 ,  #296

**Comment by abazudosen** [comment]
33 error node v7.4.0
34 error npm  v4.1.1
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/boostrap
37 error 404
38 error 404 'boostrap' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
 

PLEASE HELP!!! I AM NEW TO NODE & ANGULAR
