### ISSUE TITLE
Cannot import a github repo due to too many repo's 

### ISSUE THREAD

**Issue by ryanstevens** [joemccann/dillinger#284]
When I navigate to `import from` -> `Organizations` -> (click my org) 

I can see a list of the repositories.  But not the one I want to click to, I think it's due to the fact the org I'm looking at has more the current screen renders.  Perhaps this overlay could scroll or implement paging.

**Comment by xianxingg** [comment]
+1

> https://developer.github.com/v3/#pagination
> Requests that return multiple items will be paginated to 30 items by default.

In dillinger/plugins/github/github.js's `Github.fetchRepos` , per_page is never set. In that only 30 repos are loaded.

**Comment by tlongren** [comment]
Will this do it?
https://github.com/joemccann/dillinger/pull/415

**Comment by tlongren** [comment]
@joemccann, want to close this since you merged https://github.com/joemccann/dillinger/pull/415 ?

**Comment by joemccann** [comment]
yes please

**Comment by tlongren** [comment]
I don't seem to be able to. Give me permissions and I'll happily manage issues and stuff like this for you.

**Comment by joemccann** [comment]
Thanks @tlongren I'll add you

**Comment by joemccann** [comment]
done

**Comment by tlongren** [comment]
Closed by #415.
