### ISSUE TITLE
script tag appears to break things (also cross site scripting)

### ISSUE THREAD

**Issue by dxa4481** [joemccann/dillinger#285]
If you type 

```javascript
<script>
``` 

and then try to use the application you will notice some very wonky behavior.

If you paste 

```
<script>alert(1)</script>
```

 you will notice several popups as it executes several times.

**Comment by JuanCaicedo** [comment]
I checked this out too and wasn't able to replicate that same problem, but I did have some other problems. I tried to write inside the script tag, and everything I typed in would multiply. 

What do you think would be the best way to deal with this, just escape that tag and have it render as plain text?

**Comment by dxa4481** [comment]
I think different markdown engines handle it differently. I've seen script tags simply removed (I think that's what github does). I've also seen javascript areas replaced with a box that says "javascript, click to execute" in the preview window and then in the rendered version it just auto executes. It's a design choice.

**Comment by ajhsu** [comment]
i found that if i was typing "<script></scr".... and the editor will going crazily copy what i'm typing...
also, if there has a <script> tag (for example: <script data-main="scripts/main" src="scripts/require.js"></script>) in my editor, it will became super slow to type..

**Comment by benjamin-albert** [comment]
As of version 3.0 all HTML is escaped (which is being discussed in #325).

This issue has been inactive quite a while so I'm closing it.
