### ISSUE TITLE
I want to know how its styled

### ISSUE THREAD

**Issue by sangyoo91** [joemccann/dillinger#288]
I would like to know where to look to find the styling markups for dillinger.io's ace editor.

It is really nice.

**Comment by mrtnbroder** [comment]
What do you mean? Are you looking for the CSS?

https://github.com/joemccann/dillinger/tree/master/public/scss

It's written in http://sass-lang.com/

...and thanks! :)

**Comment by sangyoo91** [comment]
@mrtnbroder  It's different from the regular ace editor that I have implemented on my website ( eac gutter height, etc) I couldn't find the snippets for the styling other than the font styling here...

**Comment by mrtnbroder** [comment]
Ahh, okay! Well that's located here: https://github.com/joemccann/dillinger/blob/master/public/js/documents/theme-dillinger.js

**Comment by benjamin-albert** [comment]
This issue has been inactive quite a while so I'm closing it.
