### ISSUE TITLE
export options not available

### ISSUE THREAD

**Issue by dcvezzani** [joemccann/dillinger#289]
I'm assuming that there is some configuration I need to tweak in order for these options to be available.  Where is the documentation for these options and how to enable them?

In previous versions of Dillinger, the export options were available by default.  Is that not the case anymore?

**Comment by joemccann** [comment]
not sure what you mean?

**Comment by misterbisson** [comment]
This may be duplicated in https://github.com/joemccann/dillinger/issues/297, which now has additional information.

I'd propose marking/closing it as a duplicate and elevating the priority of the fix in #297.

**Comment by dcvezzani** [comment]
I'll keep an eye on #297 as suggested.  Thanks!
