### ISSUE TITLE
Adjustable line-height

### ISSUE THREAD

**Issue by danvk** [joemccann/dillinger#291]
dillinger.io uses `body { line-height: 2rem }`. I find this to be a bit too loose for comfortable reading. I usually tweak it using Chrome's dev tools before copy/pasting out of Dillinger.

It would be awesome if the `line-height` setting could be customized. Or, even better, if there were support for custom stylesheets.

**Comment by danvk** [comment]
Well, one easy workaround is to put this at the top of your Markdown :)

```html
<style>body { line-height: 20px; }</style>
```

**Comment by joemccann** [comment]
Support for custom stylesheets is a feature we should definitely elevate.  I've wanted this for some time and then would be possible to export custom styles to PDF, HTML, etc.
