### ISSUE TITLE
Pre-processor capability?

### ISSUE THREAD

**Issue by mtwomey** [joemccann/dillinger#293]
Is there a convenient place I could hook in a custom pre-processor? I'd like to write a custom processor that can deal with a few custom tags prior to the plain text hitting the main markdown processor.

**Comment by joemccann** [comment]
feel free to have at it

**Comment by mtwomey** [comment]
Sure - my question is if there is a "right" place to inset it into the processing chain?

**Comment by benjamin-albert** [comment]
This issue has been inactive quite a while so I'm closing it.
