### ISSUE TITLE
angular-bootstrap "No compatible version found"

### ISSUE THREAD

**Issue by dandavison** [joemccann/dillinger#296]
I'm following the install instructions in the dillinger README.md with dillinger at 9acc834ac4e7eff4f57086992f7aea1186b70272. package.json specifies `"angular-bootstrap": "^0.11.0"`. I can't get that to work (below). If I change it to `>=0.11.0` the npm install does work fine, installing angular-boostrap 0.12.0. Is this user error at my end or is there a bug in dillinger's install instructions / package.json?

```
/private/tmp/dillinger npm i -d
npm info it worked if it ends with ok
npm info using npm@2.5.1
npm info using node@v0.10.33
npm info preinstall Dillinger@3.0.4
npm info attempt registry request try #1 at 15:03:37
npm http request GET https://registry.npmjs.org/angular-bootstrap
npm http 304 https://registry.npmjs.org/angular-bootstrap
npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-d"
npm ERR! node v0.10.33
npm ERR! npm  v2.5.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: angular-bootstrap@'>=0.11.0 <0.12.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.12.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/dillinger/npm-debug.log
```

**Comment by reinaldorauch** [comment]
have same issue here

**Comment by alexanderjeurissen** [comment]
You can fix this by manually editing the `package.json` file and changing the version of angular-bootstrap from `^0.11.0` to `0.12.0`

**Comment by alexanderjeurissen** [comment]
see #280

**Comment by merolorem** [comment]
Hi.

remote: 514 error notarget No compatible version found: angular-bootstrap@'>=0.11.0-0 <0.12.0-0'
remote: 514 error notarget Valid install targets:
remote: 514 error notarget ["0.12.0"]
remote: 514 error notarget
remote: 514 error notarget This is most likely not a problem with npm itself.
remote: 514 error notarget In most cases you or one of your dependencies are requesting
remote: 514 error notarget a package version that doesn't exist.
remote: 515 error System Linux 3.13.0-40-generic
remote: 516 error command "/tmp/build_925d6cd4a6cdbaf8c5fbda3945874307/vendor/node/bin/node" "/tmp/build_925d6cd4a6cdbaf8c5fbda3945874307/vendor/node/bin/npm" "install" "--userconfig" "/tmp/build_925d6cd4a6cdbaf8c5fbda3945874307/.npmrc" "--production"
remote: 517 error cwd /tmp/build_925d6cd4a6cdbaf8c5fbda3945874307
remote: 518 error node -v v0.10.37
remote: 519 error npm -v 1.4.28
remote: 520 error code ETARGET
remote: 521 verbose exit [ 1, true ]
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to heroku...

Same story..

Tryin to deploy on heroku without success..

I change.
  "dependencies": {
    "angular-bootstrap": "0.12.0",

A way to get 0.11.0 ?

Regards

**Comment by joemccann** [comment]
@mrtnbroder can you have a look here?  I'm digging through and it appears when upgrading to `angular-bootstrap` 0.12, angular is then not being added in the webpack build.  

I suspect it has to do something in the `webpack.config.js` file.  

The error shows Angular just need being added/required.

![screen shot 2015-03-18 at 12 25 17](https://cloud.githubusercontent.com/assets/48234/6715047/efd98e44-cd69-11e4-9f4f-140c5e5be164.png)

**Comment by misterbisson** [comment]
@joemccann @mrtnbroder any thoughts on this one?

**Comment by joemccann** [comment]
should be resolved now
