### ISSUE TITLE
Dillinger is getting slow

### ISSUE THREAD

**Issue by yuhua-chen** [joemccann/dillinger#301]
I was writing about 250 lines+ and the Dillinger is getting slow, especially typing in Chinese. Please find out what happened. Thanks! Dillinger is the best one of online editor for markdown. :+1:

**Comment by joemccann** [comment]
Most likely the update of the entire UI on each keypress. If we used React and only updated the deltas we would see a performance increase.

**Comment by yuhua-chen** [comment]
Thanks for reply. Looking forward to it :grinning:

**Comment by joemccann** [comment]
Well someone will need to write the code!

**Comment by ZuBB** [comment]
Just want to let you know that same thing is with Cyrillic

ps: https://stackedit.io/editor behaves much smoothly

**Comment by benjamin-albert** [comment]
Let's continue this discussion in #198
