### ISSUE TITLE
Cannot select/copy/paste text in Chrome on Android

### ISSUE THREAD

**Issue by bmcbride** [joemccann/dillinger#304]
For some reason I cannot seem to get text selection working in the editor on Chrome for Android. It works everywhere else on the site, except for the markdown editing screen (with line numbers). This is especially cumbersome when you create a new document, which is filled in with 120+ lines of text that need to be removed. Awesome mobile web app nevertheless!

**Comment by joemccann** [comment]
Super bizarre bug.  Must be with the browserified version of the Ace editor; this is what Dillinger uses for the text editor bit.  Maybe file a bug there?

**Comment by bmcbride** [comment]
Looks like there's already an issue filed here: https://github.com/ajaxorg/ace/issues/2265

**Comment by mageddo** [comment]
No they don't. Same issue today https://ace.c9.io/build/kitchen-sink.html

**Comment by lorenx** [comment]
I have to reopen cause I'm experiencing the same issue.

You can watch it here: https://i.imgur.com/olA0bqr.mp4
I can freely select any text except inside the editor.

The same thing happens with Brave and DuckDuckGo browsers so I'm not sure it's Chrome related.

Android: 8.1.0
Chrome: 86.0.4240.185
