### ISSUE TITLE
Feature requests: More integration plugins [bounty]

### ISSUE THREAD

**Issue by za3k** [joemccann/dillinger#308]
I'd love to run Dillinger on my webserver, but I don't like storing data in cloud services--I want control of my data. Use case: edit my website, which is in Markdown.

I have two plugins I'm requesting:
1. Edit local files in a specified directory (Easy!)
2. Edit files in any (SSH) git repo with supplied access credentials (Difficult!)

I'm willing to pay a $10 bounty each if someone writes either Dillinger plugin. That's not enough to justify the work on its own, I just want to show my appreciation for anyone that does this. I can use Paypal or whatever digital method works best in your country

**Comment by benjamin-albert** [comment]
Git is distributed, which means that to make changes to a git repo you need to clone the repo to the machine that runs Dillinger, make the commits and push them to the remote via SSH.

So basically if you could have a desktop version of Dillinger that could open, edit and save to any local directory on your machine you could:
1. Open your websites working directory in Dillinger on your own machine.
2. Make and save the change to your working directory (again on your own machine).
3. Commit the changes via any git client.
4. Push the commits via SSH with any git client.

@za3k If you think that Dillinger as desktop app would work for you then we can just consider this another desktop app feature request.

**Comment by za3k** [comment]
Yes, understood how git works. Not exactly sure what I was thinking since I posted this a year ago--I had to look up what Dillinger was.

It's unclear to me what "desktop app" means here. If you mean that server-side support would be needed for SSH push, yes, that's prooobably true, although I'm not sure what's possible with sockets. Although, if you wanted to target e.g. only github, you could probably do it without SSH (they have an API).

I wouldn't be surprised if someone has implemented git in javascript already, minus SSH for push access--if not, I could probably do that? There are some fairly minimal packages in node for SSH. Agreed it's probably easier to just use the command-line git client if it's going to be locally hosted.

I don't think your workaround is really providing the convenience an actual user would need, but some kind of desktop app that did this automatically would be in keeping with the bounty enough for me to pay it, even if I wouldn't use it.

**Comment by benjamin-albert** [comment]
What a mean by desktop app is running Dillinger (and it's server) on your local machine as an [electron app](http://electron.atom.io).

This way Dillinger has easy read and wite access to your local working tree and online services are not required for publishing.

@za3k If a desktop app is not an ideal solution for you perhaps you can describe a use case of the ideal solution you have in mind.
