### ISSUE TITLE
Dillinger Stuck at "Prepping all the things" when run locally

### ISSUE THREAD

**Issue by ethanluoyc** [joemccann/dillinger#309]
After changing  the version of angular-bootstrap to 0.12.0 according to [this](https://github.com/joemccann/dillinger/issues/296), I now cannot run Dillinger locally as it will be stuck at the prepping page

![screen shot 2015-03-15 at 13 08 30](https://cloud.githubusercontent.com/assets/6040760/6654759/6a5eb304-cb14-11e4-83b7-5c503bbbd291.png)

Not sure if this is a bug or not.

**Comment by JuanCaicedo** [comment]
I get the same thing. If I look in the network tab, there is an error pulling in `webpack-dev-server.js` as well as `assets/bundle.js`. Do you see the same thing?

**Comment by JuanCaicedo** [comment]
If I try to run it I get the same problem. After running `node app.js` and `gulp watch`, the app hangs. In the console, I can see the following error:
````
Uncaught ReferenceError: require is not defined      index.js?./~/exports-loader?angular:1 Uncaught ReferenceError: require is not defined
````

**Comment by ethanluoyc** [comment]
@JuanCaicedo  Yes I get the exact same problem

**Comment by moonhound** [comment]
Oh good I'm not the only one having this happen. I get the require errors regardless of fixing Angular's inability to build using the solution from #296 or #280. http://paste.ee/p/pP0sp has a full (sans gulp install) install log and what happens afterwards, if that's useful.

The require statement my browser complains about being undefined does not seem to appear in the bundle.js presented by http://dillinger.io.

**Comment by b0elter** [comment]
If integrations are not required, a workaround is to skip any gulp steps. Running only `npm install` and `node app.js` was sufficient for me.

**Comment by joemccann** [comment]
@mrtnbroder I can confirm that upgrading to 0.12 of Angular in the `package.json` breaks the `bundle.js` file.

Can you have a look at what is happening when the `bundle` is being created?  I had a look but without any documentation it is hard for me to debug why `bundle.js` is broken?

**Comment by misterbisson** [comment]
@joemccann @mrtnbroder any thoughts on this one?

**Comment by joemccann** [comment]
@mrtnbroder this is release blocker.  We actually can't do anything moving forward with updating dillinger.io without getting this issue resolved.  I did a bunch of digging but with any documentation I'm coming up empty on what to do next.  Can you please have a look?

**Comment by mrtnbroder** [comment]
Sorry for taking so long, totally overwhelmed with work. Please take a look @joemccann and see if this fixes it!
