### ISSUE TITLE
Use virtual-dom for performance

### ISSUE THREAD

**Issue by lookfirst** [joemccann/dillinger#311]
Re-drawing the entire DOM of the preview pane every time someone types something is pretty inefficient, especially when you have a lot of images or other resources that are hard to draw (MathML?).

If you use [virtual-dom](https://github.com/Matt-Esch/virtual-dom) to do diff'ing of the changes, that will improve performance quite a bit.

**Comment by joemccann** [comment]
great! feel free to submit a Pull Request

**Comment by mrtnbroder** [comment]
I had the same Idea some weeks ago, I am just so buys at the moment... it should only take a couple of hours to implement.

**Comment by paulocheque** [comment]
I am helping to implement a similar editor with preview and we are trying to use virtual-dom (https://github.com/pluralsight/guides-cms/pull/47). It is not perfect yet, but it could be a start point.

**Comment by benjamin-albert** [comment]
Let's move this conversation to #198 (Convert Dillinger to a SPA).
