### ISSUE TITLE
Custom HTML Stylesheet

### ISSUE THREAD

**Issue by ktodyruik** [joemccann/dillinger#315]
Hi,

Dillinger is a really nice markdown editor. However, sorry to say this, but the Styled HTML export in Dillinger is... errrr... well... ugly.

Is is possible to change the stylesheet in the Styled HTML export in Dillinger? Either in the markdown source, or in the editor?

Could the default styled html stylesheet be improved to something clean, with a white background, and with some margins? 

There are many nice examples on the web. Here is a nice example of clean typography and layout:
http://kevinburke.bitbucket.org/markdowncss/

Thanks

**Comment by joemccann** [comment]
Feel free to make your changes and submit a pull request

On Thursday, April 9, 2015, ktodyruik <notifications@github.com> wrote:

> Hi,
>
> Dillinger is a really nice markdown editor. However, sorry to say this,
> but the Styled HTML export in Dillinger is... errrr... well... ugly.
>
> Is is possible to change the stylesheet in the Styled HTML export in
> Dillinger? Either in the markdown source, or in the editor?
>
> Could the default styled html stylesheet be improved to something clean,
> with a white background, and with some margins?
>
> There are many nice examples on the web. Here is a nice example of clean
> typography and layout:
> http://kevinburke.bitbucket.org/markdowncss/
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/315>.
>


-- 
Sent from Joe In Real Life

**Comment by charmpitz** [comment]
I agree with ktodyruik, imo the old styles were the best, new ones are just ugly. :)

**Comment by joemccann** [comment]
Vote with your pull request

On Monday, April 20, 2015, Andrei Pit <notifications@github.com> wrote:

> I agree with ktodyruik, imo the old styles were the best, new ones are
> just ugly. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/315#issuecomment-94515704>.
>


-- 
Sent from Joe In Real Life

**Comment by rdallaire** [comment]
It would be nice to have different 'themes' or styles, such as a github one style that matches what github looks like. I might mess around with this if I have time.

**Comment by joemccann** [comment]
No traction here so i'm closing.
