### ISSUE TITLE
HTML is escaped in preview

### ISSUE THREAD

**Issue by jmm** [joemccann/dillinger#325]
Shouldn't most HTML be left alone? If I enter:

``` html
<i>italic</i>
<em>whatever</em>
<a href="blah">blah</a>

<ul>
<li>
one
</li>
</ul>
```

I get the following literal output in the preview pane:

```
<i>italic</i> <em>whatever</em> <a href="blah">blah</a>

<ul> <li> one </li> </ul>
```

This is in Chrome 42 / Firefox 37 (Win 7 x64).

**Comment by idleberg** [comment]
+1

**Comment by Xarcell** [comment]
That would defeat the purpose of the application. As it says in the preview:

> The overriding design goal for Markdown's
> formatting syntax is to make it as readable
> as possible. The idea is that a
> Markdown-formatted document should be
> publishable as-is, as plain text, without
> looking like it's been marked up with tags
> or formatting instructions.

To achieve what your trying to do, don't use HTML, use markdown syntax:

    *whatever*

    [blah](http://blah.com)

    * One

This issue should be closed.

Which makes it easier for humans to read, especially those without HTML knowledge.

**Comment by idleberg** [comment]
I agree that ideally, there'd be no need to mix HTML with Markdown — for the same reasons you have quoted. The main reason for *people* using HTML is Markdown are the limitations of the latter, and I haven't given up the hope that CommonMark will ultimately fix the shortcomings of Markdown. However, major Markdown-flavours such as GitHub Flavoured Markdown (GFM) and CommonMark both allow HTML inside Markdown at this point. Dillinger is a great tool to test Markdown documents, though if it wasn't for neat extras like localStorage, I could as well use [try.commonmark.org](http://try.commonmark.org). For me personally, the only reason to mix HTML with Markdown is the `<kbd>`-tag as it's useful for software documentation. I'd be more than happy to adopt an alternative in Markdown syntax, but obviously John Gruber has no interest in the further development of Markdown.

On the other hand I have some respect for you not trying to polute your viewer with non-standard syntax (not that there is a real standard). Maybe some future version of Dillinger could let the user specify a preferred Markdown-flavour. That, in my eyes, is probably a solution that would serve everyone best.

**Comment by jmm** [comment]
@Xarcell Long story short...:
> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself.

http://daringfireball.net/projects/markdown/syntax#html

You may have mistaken my reduced test case as an example of something specific I was trying to do. It can just as well be repro'd (when the problem is happening) with:
```html
<table>
    <tr>
        <td>Foo</td>
    </tr>
</table>
```

It's also unfortunate that as soon as you use a block-level tag, you can't use markdown anymore inside it.

**Comment by benjamin-albert** [comment]
As mentioned in #305 

> 
> Since switching to Markdown-it in version 3 all HTML is escaped (both in the preview and exported document).
> 
> We can consider changing this in the next major release.

**Comment by jmm** [comment]
Hmm, this seems to make for a very niche tool. HTML is essentially integral to Markdown authoring since Markdown itself is so limited. As quoted earlier from its [docs](http://daringfireball.net/projects/markdown/syntax):

> For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags.

How does that reconcile with escaping HTML?

Also, that's not how Markdown authoring / rendering work on GitHub and StackOverflow, for example.

**Comment by benjamin-albert** [comment]
@jmm I 100% agree, I defiantly think we should allow html rendering.

In fact rendering HTML in the preview can be achieved easily by passing `html: true` to the `Markdown-it` constructor.

But I don't think this was disabled for no good reason.

Here is an example of a security problem enabling HTML can cause:
![screen shot 2016-05-04 at 9 28 13 pm](https://cloud.githubusercontent.com/assets/5201428/15024894/78967b3c-123f-11e6-88ec-c05cb86da49f.png)

Before I enable html rendering I want to make sure we 100% understand what security holes this opens us up to.

I think safe HTML rendering should be one of our objectives when we rewrite the preview with React.

All React related talks are found on #198, so let's continue this conversation over there.

**Comment by jmm** [comment]
@benjamin-albert I'm surprised if the previous version didn't sanitize HTML and I'm surprised the parser was changed without accounting for that, since the usefulness seems so limited to me without HTML. I see that the Markdown-it docs say:

> You may need external [HTML] sanitizer

I don't know the options, but I imagine there must be some good HTML sanitizers that allow stuff like whitelisting tags and attributes.

I'd like to make a suggestion that you have a dedicated issue to track this (i.e. reopen this issue) since fixing it may have little or no connection to rewriting the preview using React. Insofar as you want to link them, perhaps assigning both to the same milestone (e.g. v4.0) would be good.

Thanks!

**Comment by benjamin-albert** [comment]
@jmm I agree that ideally this shouldn't be tied to the React rewrite.

However there's only a hand full of people how are actually contributing code (and triaging issues) for this project.
I prefer that those limited people focus on a much better Dillinger (which will include safe HTML rendering).

Until we implement this feature with React, anyone can feel free to:
 Ask a question on the relevant [Stack Exchange](http://stackexchange.com/) site about:
   1. Should we use a white or blacklist of tags and attributes.
   2. What tags should be supported and what should not be escaped.
   3. What tools should we use to sanitize the HTML (this doesn't necessarily need to be asked).

After that Implement this feature and open a pull request.

I also agree that it's better of keeping this in it's own issue, so I'm reopening this issue.

**Comment by benjamin-albert** [comment]
Of course looks like the these questions have been asked on stack exchange before.  See: [What HTML tags are allowed on Stack Exchange sites?](http://meta.stackexchange.com/a/135909)
