### ISSUE TITLE
Using backticks and pipes inside a table breaks layout on dillinger.io

### ISSUE THREAD

**Issue by okdewit** [joemccann/dillinger#326]
one | two
    ----- | -----
    ```helloworld``` | two columns, as it should be.
    ```hello|world``` | two columns on github, three columns on dillinger!

Luckily this has been fixed very recently in markdown.it itself I think:
Discussion: https://github.com/markdown-it/markdown-it/pull/87
Commit: https://github.com/markdown-it/markdown-it/commit/866faa151603a31d4cc177d78ebcd2ab7edf4df7

So fixing this issue should be as simple as pushing a new build to the website.

Thanks for the awesome product!

**Comment by joemccann** [comment]
I believe we use `marked` not `markdown-it`.

**Comment by okdewit** [comment]
Ah, I'm not that familiar with the code of Dillinger and saw Markdown-it as a dependency, didn't notice Marked was also in there.

Problem seems to exist in that library as well, with an existing open issue. (https://github.com/chjj/marked/issues/285)

**Comment by benjamin-albert** [comment]
Looks like it works when you use the `\` escape character.

![screen shot 2016-05-02 at 8 21 24 pm](https://cloud.githubusercontent.com/assets/5201428/14961855/a1c74d66-10a4-11e6-808f-e7b1a417e3ae.png)

@joemccann Looks like we are using `markdown-it`. I think we can close this issue now.
![screen shot 2016-05-02 at 8 32 53 pm](https://cloud.githubusercontent.com/assets/5201428/14961964/2ca5a0cc-10a5-11e6-8ab5-39ed60392e45.png)

**Comment by joemccann** [comment]
should we close this issue?

**Comment by benjamin-albert** [comment]
It works for me so I guess we should close it.

Worse case we can re-open it.
