### ISSUE TITLE
Markdown -> HTML conversion incorrectly handles apostrophe character ( ' ) in header links compared to markdown

### ISSUE THREAD

**Issue by King-of-Spades** [joemccann/dillinger#327]
## Overview

I noticed when using the web-page tool version of the converter here: http://dillinger.io/, that the apostrophe character ( ' ) in a header is generates an inconsistent in-line link target compared to vanilla markdown. 
## Sample

Example that works as expected in markdown:

```
[My foo doesn't go bar](#my-foo-doesnt-go-bar)

#### My foo doesn't go bar
```

[My foo doesn't go bar](#my-foo-doesnt-go-bar)
#### My foo doesn't go bar

> If you click the link inspector for the header, you will see it appends `#why-doesnt-my-foo-go-bar`
## Expected result:

`<h4 id="my-foo-doesnt-go-bar">`
## Actual result:

`<h4 id="my-foo-doesn-t-go-bar">`
## Conclusion:

The link should have a consistent handling of the apostrophe character relative to how the in-line link reference is handled in markdown; so that the use of the apostrophe doesn't break in-line linking.

**Comment by King-of-Spades** [comment]
I didn't realize that the issue page would ignore my sample in-line links; here's a screencast demonstrating the 'expected' result though: http://screencast.com/t/vJOeB6ViKbT

**Comment by joemccann** [comment]
Appears to be an issue with the `marked` module itself.

**Comment by joemccann** [comment]
Unfortunately this is an issue with the way Ace Editor renders the anchor tags.
