### ISSUE TITLE
Something weird is happening to the cursor in Dillinger

### ISSUE THREAD

**Issue by alexbooker** [joemccann/dillinger#334]
Here is a GIF that demonstrates the bug:

![](http://i.imgur.com/NzeAZvz.gif)

([Direct link](http://i.imgur.com/NzeAZvz.gif))

**Comment by Xarcell** [comment]
What browser and version are you using? Need more info to see if the problem can be reproduced.

**Comment by joemccann** [comment]
Yes, I've seen this sporadically as well.  I believe it has to do with the Ace Editor itself

**Comment by benjamin-albert** [comment]
@alexbooker We at least need the browser and OS versions so we can reproduce this issue.

If you can give us this information we can reopen this issue see what we can do.
