### ISSUE TITLE
Scroll sync does not work when self-hosting

### ISSUE THREAD

**Issue by dasJ** [joemccann/dillinger#341]
I am self hosting Dillinger behind an nginx.
However, scroll sync does not work. It is disabled and clicking the option does nothing. The firefox console shows no errors at all.
Are there more installation steps required to get this to work?

**Comment by joemccann** [comment]
are you building with gulp first?

`gulp build --prod`

**Comment by benjamin-albert** [comment]
This issue has been inactive quite a while so I'm closing it.

@dasJ If you can tell us what you've tried we can reopen this issue.
