### ISSUE TITLE
PDF export fails to work

### ISSUE THREAD

**Issue by harriha** [joemccann/dillinger#346]
Just noticed that the PDF export doesn't seem to work, I see this in the console:

> http://dillinger.io/files/pdf/Something%20wrong%20with%20the%20pdf%20conversion. Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by joemccann** [comment]
yup something broke on the pdf conversion..not sure what..maybe version of
phantomjs?

**Comment by joemccann** [comment]
fixed! just needed up upgrade npm

**Comment by harriha** [comment]
Thanks :+1:
