### ISSUE TITLE
Misspelling in sample document final comment

### ISSUE THREAD

**Issue by sondy** [joemccann/dillinger#365]
At the end of the sample "Untitled document.md" that appears when you visit dillinger.io in your browser, the final comment reads

> (These are reference links used in the body of this note and get stripped out when the markdown processor does it's job. There is no need to format nicely because it shouldn't be seen. Thanks SO - http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax)

The "it's" should be replaced with "its".

**Comment by tlongren** [comment]
https://github.com/joemccann/dillinger/pull/416
