### ISSUE TITLE
Labeled links in PDF not working

### ISSUE THREAD

**Issue by joe776** [joemccann/dillinger#374]
Labeled links in the PDF are rendered as links, however they are just normal text and clicking does not open the URL. For example:

`https://github.com/` -> correctly generates a link in the PDF
`[GitHub](https://github.com/)` -> looks the same, however it is just text

Preview and HTML generation works fine.

**Comment by joemccann** [comment]
Maybe an issue with PhantomJS?

On Wed, Oct 7, 2015 at 10:09 AM, Joerg Schoenfisch <notifications@github.com

**Comment by joe776** [comment]
I have no idea of the inner workings of dillinger, to be honest. I just noticed this while using dillinger.io.
Is there anything I can do to help diagnose the issue? I took a quick glance at the code, but could make much sense of it right now.

**Comment by joemccann** [comment]
PDF generation happens with PhantomJS.  I would start looking over there

**Comment by joe776** [comment]
OK, there is an open issue in PhantomJS for this: ariya/phantomjs#10196
Essentially it is a problem with Qt, which was only recently fixed and will hopefully be integrated in PhantomJS soon; probably version 2.0.1: https://github.com/ariya/phantomjs/pull/13250

**Comment by benjamin-albert** [comment]
I've recently refactored document export, see #511

During the process I updated PhantomJS (to version 2.1.5) and looks links are working in PDF export now.

@joemccann I think we can close this issue now.

**Comment by joemccann** [comment]
did this require an update to dillinger/master?

**Comment by benjamin-albert** [comment]
@joemccann Yes, it required deplying Dillinger after merging my pull request.

You can see all the details in #511

**Comment by joemccann** [comment]
awesome thanks!

**Comment by benjamin-albert** [comment]
In order to reuse a single instance of PhantomJS I installed the [phantom](https://www.npmjs.com/package/phantom) module which depends on [phantom-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) which implicitly installs the latest version (2.1.5 on my Mac) for the platform your running on.

**Comment by joemccann** [comment]
gotcha
