### ISSUE TITLE
error in gulp build --prod

### ISSUE THREAD

**Issue by saitodisse** [joemccann/dillinger#378]
Hello,
I'm trying to buid with `gulp --prod` but I'm getting this error bellow: 

```
gulp build --prod
[16:04:08] Using gulpfile ~/_git/button-projects/dillinger/gulpfile.js
[16:04:08] Starting 'build'...
[16:04:08] Starting 'webpack:build'...
[16:04:08] Starting 'sass'...
[16:04:08] Finished 'build' after 71 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property '1' of null
    at module.exports (/...myprojects/dillinger/node_modules/gulp-group-css-media-queries/node_modules/group-css-media-queries/index.js:37:14)
```

> In dev mode everything is working correctly. `gulp build` works, but `gulp build --prod` dont

I've already opened an issue on https://github.com/SE7ENSKY/group-css-media-queries/pull/8 but I'm still not sure if this will fix this error.

**Comment by joemccann** [comment]
Yeah I've spend the past hour trying to track it down and that module is definitely the issue.  Not sure what to do.

**Comment by joemccann** [comment]
run

`npm i -d --save-dev`

and you'll get the latest version that fixes this bug  SE7ENSKY/group-css-media-queries#8

**Comment by tomkur** [comment]
Hi! I was doing a first, clean install of dillinger today and I still got this problem. What am I missing?

**Comment by joemccann** [comment]
Don't use npm 3

Run node v 4

On Thursday, October 15, 2015, tomkur <notifications@github.com> wrote:

> Hi! I was doing a first, clean install of dillinger today and I still got
> this problem. What am I missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/378#issuecomment-148333980>
> .
>


-- 
Sent from Joe In Real Life

**Comment by saitodisse** [comment]
Hi @joemccann, hi @tomkur.
The problem was not solved yet because the fix was made on https://github.com/SE7ENSKY/group-css-media-queries/pull/8. Dillinger depends on https://github.com/avaly/gulp-group-css-media-queries.

There is many things to be made:

- `group-css-media-queries` must publish a patch
- `gulp-group-css-media-queries` update dependency and publish a patch
- `dillinger` the same thing: update dependency and publish a patch

For now there two ways to get going:

1) run dev version

```sh
npm install
gulp build
node app
```

2) run prod version and apply patch yourself. I did this with `wget`:

```sh
wget https://raw.githubusercontent.com/saitodisse/group-css-media-queries/71fe8b181650b20790aca325988ac0fb9d9fe4a4/index.js -O ./node_modules/gulp-group-css-media-queries/node_modules/group-css-media-queries/index.js

wget https://raw.githubusercontent.com/saitodisse/group-css-media-queries/71fe8b181650b20790aca325988ac0fb9d9fe4a4/index.js -O ./node_modules/group-css-media-queries/index.js
```
> I'm applying this at two places because I don't know where your npm will throw this dependency. Depends on npm version.

**Comment by joemccann** [comment]
easy pull request!

**Comment by tomkur** [comment]
Thanks, @saitodisse, I'll check that.

**Comment by tomkur** [comment]
Thanks, @joemccann, I'm using npm 2.14.4 and node 4.1.1, so I guess it's not a problem.

**Comment by joemccann** [comment]
yeah this is still an issue.

easy to reproduce

```
npm clean cache
git clone https://github.com/joemccann/dillinger.git && cd dillinger
npm i --save-dev
gulp build --prod
```

**Comment by joemccann** [comment]
fixed with latest version being published of group-css-media-queries package

**Comment by saitodisse** [comment]
Good job. Works very well.
