### ISSUE TITLE
Github authorize / import / save is pretty clunky

### ISSUE THREAD

**Issue by timeslicelive** [joemccann/dillinger#402]
I'm finding it really difficult to edit documentation for a project I'm a collaborator on.

**1 - Authorizing GitHub is clunky.**

There's a page reload, then you're back the starting page.
You have to then re-click "Import from Github" to show the import panel. This really should just show on reload.

**2 - The repos I'm a collaborator for, don't show in the list**

I've tried numerous things, but I just can't see them. In the end, I had to 
- delete dillinger's site cookies
- re-authorize github as the user for the repo I'm a contributor for
- do the usual import route to edit the files

If I didn't have login for these repos, how would I edit multiple accounts?

**3 - Dillinger's document list doesn't give you any information other than the document title as to what the document is**

Could do with improvement here.
Prose.io seems to have had more development time in this aspect of the project, and it shows. 

Would be great if dillinger could catch up.

Thanks for all the hard work, and free product!

Dave

**Comment by joemccann** [comment]
Seems like a great Pull Request to land.  Get going!

**Comment by davestewart** [comment]
Hi Joe,

I signed in with the wrong account!

Wouldn't it :) Unlikely though :(

I'll be beavering away on my own OS projects; I have too many on to really be of any use to something like this which would certainly entail a learning curve.

Hopefully this issue will go some way to highlighting the UX issue though.

Thanks again,
Dave

**Comment by julmot** [comment]
> You have to then re-click "Import from Github" to show the import panel. This really should just show on reload.

I totally agree here!

> Dillinger's document list doesn't give you any information other than the document title as to what the document is

I agree here too. I have several folders which just contain a file "article.md", therefore all filenames are equiially. 

Lastly I'd like to add one thing to the list: The file chooser dialog should be hierarchically grouped by folders (files should only appear if you click on a folder).
