### ISSUE TITLE
AWS S3

### ISSUE THREAD

**Issue by amlwwalker** [joemccann/dillinger#466]
This is a really awsome app. 
What would be really cool is if you could use S3 buckets as the storage location. Im looking at this from a start up perspective - be great if users could have permissions on buckets and therefore what they can see and use dillinger as the collaborative editor

**Comment by joemccann** [comment]
In what way do you want to use S3? To save the markdown files?

On Sunday, November 29, 2015, Alex Walker <notifications@github.com> wrote:

> This is a really awsome app.
> What would be really cool is if you could use S3 buckets as the storage
> location. Im looking at this from a start up perspective - be great if
> users could have permissions on buckets and therefore what they can see and
> use dillinger as the collaborative editor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/466>.
>


-- 
Sent from Joe In Real Life

**Comment by benjamin-albert** [comment]
@amlwwalker If you can tell us what you need S3 for we can reopen this issue.
