### ISSUE TITLE
Import File as UTF-8

### ISSUE THREAD

**Issue by wellyal** [joemccann/dillinger#471]
I have this [file](https://github.com/wellingtonamaralleitao/roundcube-helper/blob/master/roundcube_helper.md) with some special characters even though when I try to import through dillinger it's breaking the utf-8. I didn't see any option to change the unicode. Heres how it shows on dillinger editor when I import my file.

![Alt text](http://snag.gy/iLxBz.jpg)

i == é
servigo == serviço

**Comment by joemccann** [comment]
looks like a bug in the import function...

**Comment by wellingtonamaralleitao** [comment]
I'll take a look. @joemccann Is there a slack room for this project?

**Comment by joemccann** [comment]
Nope but there should be!

On Friday, December 4, 2015, Wellyngton Amaral Leitão <
notifications@github.com> wrote:

> I'll take a look. @joemccann <https://github.com/joemccann> Is there a
> slack room for this project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/471#issuecomment-162021017>
> .
>


-- 
Sent from Joe In Real Life

**Comment by joemccann** [comment]
This is fixed.
