### ISSUE TITLE
Marked or Markdown-it?

### ISSUE THREAD

**Issue by tscok** [joemccann/dillinger#474]
The readme has me confused in this matter. It says you're using "Marked - a super fast port of Markdown to JavaScript" yet in your code there are quite a few references to Markdown-it. Are you using both? Or have you just forgotten to update the readme? In case you're not using marked anymore, what was the reasoning behind this? Just want to know more about parsing .md :smile:

**Comment by joemccann** [comment]
Hmm interesting...I thought we were using "marked" but maybe in the
redesign we switched to marked-it?

**Comment by benjamin-albert** [comment]
As I've mentioned in [this comment](https://github.com/joemccann/dillinger/issues/326#issuecomment-216305240) in #326 we are using `Markdown-it`.

We've recently merged a pull request (#515) that updated the realm.

I'm closing this issue now.
