### ISSUE TITLE
fixed title in editor

### ISSUE THREAD

**Issue by httpete-ire** [joemccann/dillinger#478]
<img width="597" alt="screenshot 2015-12-10 15 40 41" src="https://cloud.githubusercontent.com/assets/1556430/11719850/7f17bc2c-9f54-11e5-9854-7eaf8e32a46e.png">

I was thinking it might be handy to keep the title area (above) of the editor fixed so the _Zen button_ can be clicked even when the page is scrolled. 

[quick screen capture of a prototype done in the dev tools](http://quick.as/4zxhb9ja)

Would anyone else want this? I can make a pull request when I get the chance

**Comment by joemccann** [comment]
Sounds good

On Thursday, December 10, 2015, Pete Redmond <notifications@github.com>
wrote:

> [image: screenshot 2015-12-10 15 40 41]
> <https://cloud.githubusercontent.com/assets/1556430/11719850/7f17bc2c-9f54-11e5-9854-7eaf8e32a46e.png>
>
> I was thinking it might be handy to keep the title area (above) of the
> editor fixed so the *Zen button* can be clicked even when the page is
> scrolled.
>
> quick screen capture of a prototype done in the dev tools
> <http://quick.as/4zxhb9ja>
>
> Would anyone else want this? I can make a pull request when I get the
> chance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/478>.
>


-- 
Sent from Joe In Real Life
