### ISSUE TITLE
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by subwaymatch** [joemccann/dillinger#481]
I'm getting this error when including Korean characters and trying to save to Github. 
Saving to Dropbox works fine. 
Please see the attached image for the console message and markdown text.  

![2015-12-12 03_10_20-online markdown editor - dillinger the last markdown editor ever](https://cloud.githubusercontent.com/assets/1064036/11751610/ea7ee6be-a07d-11e5-83a9-fb34dcf7f614.png)
![2015-12-12 03_10_45-online markdown editor - dillinger the last markdown editor ever](https://cloud.githubusercontent.com/assets/1064036/11751621/f8fa33ce-a07d-11e5-89af-06a8714811d7.png)

**Comment by benjamin-albert** [comment]
[public/js/plugins/github/github.service.js](https://github.com/joemccann/dillinger/blob/master/public/js/plugins/github/github.service.js#L196) uses the [WindowBase64.btoa()](https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/btoa#Unicode_strings) method.

The [Unicode strings] (https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/btoa#Unicode_strings) section explains exactly this problem.

Looks like an easy fix.

**Comment by joemccann** [comment]
let's do it!
