### ISSUE TITLE
Import from personal Github: Showing projects in organization's repos

### ISSUE THREAD

**Issue by dshgna** [joemccann/dillinger#486]
Hi!

I am trying to import files from a public repo in my personal account. However, Dillinger shows the repos of an organization I belong to.

Thanks in advance for any pointers to resolve this issue! I've really enjoyed using Dillinger except for this snitch.

![1](https://cloud.githubusercontent.com/assets/4735649/12047772/165e6db8-aef7-11e5-82e2-b472ea095083.PNG)
![organization_repos](https://cloud.githubusercontent.com/assets/4735649/12047773/1664da72-aef7-11e5-88d3-b9ff1cb67ca7.PNG)

**Comment by joemccann** [comment]
Invalidate the oauth token in GitHub. Try it again

**Comment by dshgna** [comment]
Thank you very much for the prompt response.

Invalidating the oauth token did not work for me. I had to restrict my organization's access to third party applications, and then invalidated oauth token. Only then was I able to view the repos in my personal account. 

Restricting third party application access is not something that all members of an organization can do, so it would be really helpfyl if this bug could be fixed.

Finally able to use Dillinger and loving it XD!
