### ISSUE TITLE
What happened to the theme support?

### ISSUE THREAD

**Issue by polarathene** [joemccann/dillinger#489]
I've seen content about 18 months old where Dillinger had a more colourful default theme along with a dropdown to change the theme. I've looked around the current layout and can't seem to find any theme options.

I'd really prefer a darker theme for writing the markdown in, along with some syntax colouring. The older preview theme also looks nice, was it removed for some reason? Or am I blind to where the theme change feature has been moved to?

[Here's a video for reference](https://www.youtube.com/watch?v=srwwb2ZA8W4).

**Comment by joemccann** [comment]
It was time for an upgrade to the UI overall and I went with a simplified
theme. Sorry! I'm open to adding it back if you want to give it a shot

On Thursday, January 21, 2016, Brennan Kinney <notifications@github.com>
wrote:

> I've seen content about 18 months old where Dillinger had a more colourful
> default theme along with a dropdown to change the theme I've looked around
> the current layout and can't seem to find any theme options
>
> I'd really prefer a darker theme for writing the markdown in, along with
> some syntax colouring The older preview theme also looks nice, was it
> removed for some reason? Or am I blind to where the theme change feature
> has been moved to?
>
> Here's a video for reference <https://wwwyoutubecom/watch?v=srwwb2ZA8W4>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/489>.
>


-- 
Sent from Joe In Real Life

**Comment by polarathene** [comment]
@joemccann I'd love to if I wasn't so swamped :) I'll stick with Atom for the time being, might come back some day if I can find time to contribute a theme. Looks like a great Markdown Editor!
