### ISSUE TITLE
performance issue with live preview turned on 

### ISSUE THREAD

**Issue by httpete-ire** [joemccann/dillinger#491]
I'm half way through building an app (college project) that is fairly similar to dillinger so I thought I would test out its performance beside dillinger.  [side by side video comparison](http://quick.as/j2yfqgrw)

I'm using the same markdown file (over 5000 lines) and dillinger really starts to slow down, I had this same issue but I __debounced__ the change event and the app feels much more responsive.

I have had a quick look through the src files but I cant find the change event that converts the markdown, can someone point me to the file so I can test if debounching the event helps. If it does I'd be happy to make a pull request  :+1:

**Comment by joemccann** [comment]
Nice work and thanks for wanting to contribute.

Should be on a keyup, keydown, or key press event is the code you're
looking for

On Saturday, January 23, 2016, Pete Redmond <notifications@github.com>
wrote:

> I'm half way through building an app (college project) that is fairly
> similar to dillinger so I thought I would test out its performance beside
> dillinger. side by side video comparison <http://quick.as/j2yfqgrw>
>
> I'm using the same markdown file (over 5000 lines) and dillinger really
> starts to slow down, I had this same issue but I *debounced* the change
> event and the app feels much more responsive.
>
> I have had a quick look through the src files but I cant find the change
> event that converts the markdown, can someone point me to the file so I can
> test if debounching the event helps. If it does I'd be happy to make a pull
> request [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/491>.
>


-- 
Sent from Joe In Real Life

**Comment by httpete-ire** [comment]
closed in #492
