### ISSUE TITLE
some code patterns break the Syntax highlighting 

### ISSUE THREAD

**Issue by seldomU** [joemccann/dillinger#493]
When the following csharp-formatted code contains the generic parameters Foo and Bar, syntax highlighting is off for for the code snippet. When they are removed, it is back on.

``` csharp
public class Test<Foo, Bar>
```

**Comment by joemccann** [comment]
I'm unable to reproduce do you have a snapshot?

**Comment by seldomU** [comment]
What is a snapshot? I just tried it again (in chrome this time) and could reproduce it. Are you including the backticks and *csharp*? I didn't know how to make them show up.

**Comment by joemccann** [comment]
screenshot, sorry

can you give me the EXACT code you are writing

**Comment by seldomU** [comment]
sure: https://imgur.com/GTltpVX

**Comment by chimericdream** [comment]
It looks like a bug in the highlight parser. C# code with generics is getting detected as arduino.

**Comment by joemccann** [comment]
@chimericdream @seldomU I'm not sure Ace Editor supports `csharp` but `java` does work. :/
