### ISSUE TITLE
Autosave during text typing

### ISSUE THREAD

**Issue by eliseealex** [joemccann/dillinger#497]
With current implementation of debounce function, autosave works only in 5 seconds after stop of typing. So, if i type fast enough (more than one character in 5 second) and accidentally close my browser tab all my work will disappear. 

I think, that it will be useful to change current implementation of debounce function so that it will save changing text every 5 second (not only in 5 second after after I finished typing).

**Comment by httpete-ire** [comment]
@eliseealex what you are talking about is throttling an event. 

I can change the debounce time to something like 1 second, unlikely that a user would quit within that second. Or I can add the throttle function to force a save after Xms

**Comment by joemccann** [comment]
yeah let's tweak it closer to 2 seconds (that's where I had it originally
set)

**Comment by eliseealex** [comment]
I meant, that it is possible yo rewrite denounce function so that it will execute at the and of each interval (for example there were two call of function in one second, first call sets interval and in the end of interval function executes with both set of arguments)
So data will be saved in the second (or two) after man stops typing and every two or five second as long as he typing.

**Comment by joemccann** [comment]
Ahh yeah that's an issue...didn't realize there were two timers running
