### ISSUE TITLE
internal server error when using google drive

### ISSUE THREAD

**Issue by sander76** [joemccann/dillinger#501]
Can't seem to import files from google drive. As soon as I choose import I get an internal server error.

**Comment by joemccann** [comment]
yes this is a bug indeed. Not sure what changed...maybe something on the Google Drive API

**Comment by uptownnickbrown** [comment]
Yes, the googleapis library has been updated with some breaking changes. It no longer exposes the googleapis.discover() function used here: https://github.com/joemccann/dillinger/blob/master/plugins/googledrive/googledrive.js#L38

They've posted a migration guide: https://github.com/google/google-api-nodejs-client/blob/master/MIGRATING.md

Doesn't look too painful - I may try to get this fixed.

**Comment by benjamin-albert** [comment]
Looks like @uptownnickbrown's PR fixed this issue I'm closing this now.
