### ISSUE TITLE
Export as PDF renders someone else's markdown document

### ISSUE THREAD

**Issue by idreyn** [joemccann/dillinger#503]
Last week I completed a homework assignment on dillinger.io and exported it to PDF in order to submit it. I received an email later on telling me that I had submitted the wrong file — in fact, the file that was exported to me was not my assignment, but rather a Dillinger-styled document titled "TP2 : Découverte du CSS3 et du SCSS I: CSS3". I haven't been able to replicate the error, but I believe that I was served a file that belongs to someone else. For what it's worth, I'm using Chrome 48.0.2564.109 on OS X 10.11. I'd rather not post either document publicly, but I'm happy to provide them over email and help in whatever way I can to resolve this issue. Thanks for your attention.

**Comment by joemccann** [comment]
Super weird -- only thing I can think is the name of your file is exactly the same as someone else's and it wasn't deleted within the same time...very rare edge case

**Comment by joemccann** [comment]
the routing is setup based on your filename...not sure how it could send you a different file
