### ISSUE TITLE
Dockerfile runs on N|Solid but does not provide console

### ISSUE THREAD

**Issue by retrohacker** [joemccann/dillinger#507]
We need to provide a `docker-compose.yml` file that provides the N|Solid console and hub to monitor the instance of Dillinger we spin up.

**Comment by sjjones85** [comment]
Hey @retrohacker and @joemccann , no worries... glad I could help (however limited).

I'm still reasonably new to Docker, so this is definitely a learning experience for me. I have had a quick look at the docker compose stuff too. I have been able to get docker-compose.yml to create a default dillinger network and join the containers to this network.  The compose file is also version 2.  https://docs.docker.com/compose/compose-file/#version-2

I run the command as follows
```sh
docker-compose -f docker-compose.yml
```

I believe I've attached to the console ok... However, I've now hit some more issues which I must admit, at this stage, I feel are out of my league for now, as per the below screenshot:
![screenshot from 2016-02-22 22-08-06](https://cloud.githubusercontent.com/assets/17245676/13235392/8a070174-d9b5-11e5-8cc7-70d212af2c6a.png)

After a little more playing, the dillinger_app1 container became a Ghost too (if my terminology is correct) - I had to reboot to finally kill it.

Nevertheless, I've committed the changes to my fork of the project if you wanted to check it out: https://github.com/sjjones85/dillinger

One word of note: in the docker-compose.yml file, you may want to change the image: property for dillinger1 as it is currently pointing to my own registry.

I hope this is of some help....
