### ISSUE TITLE
GitHub import does not have any pagination

### ISSUE THREAD

**Issue by chimericdream** [joemccann/dillinger#508]
With more than 30 repositories, there is no way to advance through the list to select repos on subsequent pages. This is related to #284, #412, #415, and #416.

It appears that the plugin correctly updates the URL as needed (as per the PRs in #415 and #416), but there aren't any forward/back buttons to actually request more pages.

**Comment by chimericdream** [comment]
It looks like the modal directive is simply missing the pagination code.

GitHub modal
https://github.com/joemccann/dillinger/blob/master/public/js/plugins/github/github-modal.directive.html

Google Drive modal (note the `pagination` block)
https://github.com/joemccann/dillinger/blob/master/public/js/plugins/google-drive/google-drive-modal.directive.html

**Comment by joemccann** [comment]
wanna add it?

**Comment by chimericdream** [comment]
I can give it a go. We'll see if I can make some time this weekend.

**Comment by joemccann** [comment]
sweet!

**Comment by koddsson** [comment]
Would it be cool if I took a stab at this?

**Comment by chimericdream** [comment]
@koddsson Yes please. I've been much busier than expected with work and home stuff, so I haven't had a chance to look at this.

**Comment by benjamin-albert** [comment]
@koddsson Yes definitely. Pull requests are welcome.
