### ISSUE TITLE
Question: is it possible to include/embed it inside of a js app?

### ISSUE THREAD

**Issue by paulocheque** [joemccann/dillinger#509]
What is the best way to include this inside of a website? Using iframes?

Is there any listeners/signals that we can use to intercept the import/save commands?

Thanks in advance

**Comment by joemccann** [comment]
Probably forking it and hosting it yourself is best bet - not sure how
Dillinger.io could be embedded

On Thursday, March 3, 2016, Paulo Cheque <notifications@github.com> wrote:

> What is the best way to include this inside of a website? Using iframes?
>
> Is there any listeners/signals that we can use to intercept the
> import/save commands?
>
> Thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/509>.
>


-- 
Sent from Joe In Real Life

**Comment by paulocheque** [comment]
I studied the code and the code would need many changes to turn it embeddable.

I created a fork and a new repository to turn Dillinger as a Bower dependency: https://github.com/paulocheque/dillinger-bower

I was able to let Dillinger embeddable, you can see in that repository, but the solution is not professional.

@joemccann Since you know all the source code, do you think it would be a good idea to change the code to be embeddable? Or this would be a crazy task?

I thought in these tasks:

- Create an Angular directives: <diillinger-editor> <dillinger-preview> <dillinger-header> <dillinger-footer>
- Then, change the scripts to package/minify only the Dillinger's code, without any dependency.
- After, we could change the code to accept custom ids, custom css etc.

I thought to create a fork for that (https://github.com/paulocheque/dillinger), but I believe would be very hard to keep this fork up to date with the core fork. What do you think?

**Comment by joemccann** [comment]
Best bet is probably to fork it.  I know @pmullr was working on an Electron app a while ago but not sure if that helps or not.
