### ISSUE TITLE
paser math latex error 

### ISSUE THREAD

**Issue by xiaokaike** [joemccann/dillinger#517]
dillinger paser latex error

``` text
\begin{cases}x-y=4\\x+y=2\end{cases}
```
### in dillinger  result

![image](https://cloud.githubusercontent.com/assets/4251499/14480976/e53ed404-0160-11e6-8778-64bbab34ffeb.png)
### in katex result

![image](https://cloud.githubusercontent.com/assets/4251499/14481003/20a179b6-0161-11e6-91ce-3a4a53f094a1.png)
### not match `xxxx$$-2x<4$$`

![image](https://cloud.githubusercontent.com/assets/4251499/14483100/06a5d718-0176-11e6-9af2-69a601ab05f6.png)

**Comment by RoyiAvital** [comment]
Have a look here:

https://github.com/joemccann/dillinger/issues/242

**Comment by xiaokaike** [comment]
@RoyiAvital  update markdown-it-math
Have a look here:
[markdown-it-math#19](https://github.com/runarberg/markdown-it-math/issues/19)

**Comment by RoyiAvital** [comment]
@xiaokaike , Well it seems it support some kind of Math.
But $$ <math> $$ should be Paragraph and $ <Math> $ should be inline.

I wish someone would just make it work like in StackEdit (https://github.com/benweet/stackedit).

**Comment by dbeecham** [comment]
https://github.com/joemccann/dillinger/pull/662 fixes this

**Comment by RoyiAvital** [comment]
@dbeecham , Is there a guide how to use Math in Dillinger?

**Comment by dbeecham** [comment]
$$a=3$$ works for me. Just be careful not to insert spaces near the $, this does not work for example: $$ x=3$$. 

Don't know of any guides unfortunately, but the library is named KaTeX, maybe there is a guide for that library somewhere. I just use the $$math$$ form.

**Comment by RoyiAvital** [comment]
@dbeecham , Math should have 2 modes:

1. Inline Math: $<LaTeX Code>$.
2. Display Math: $$<LaTeX Code>$$.

It seems you only implemented Inline Mode using the escape of Display Math.

**Comment by dbeecham** [comment]
@RoyiAvital I didn't implement this. :) do a git-blame on config.json to see who added the library in the first place. Although I agree, and of course inline mode should be a single $, and display mode should be $$...
