### ISSUE TITLE
New tab shortcut isn't working

### ISSUE THREAD

**Issue by avinoth** [joemccann/dillinger#518]
Running on Firefox 40.03. The shortcut for new tab `ctrl+t` isn't working for sometime now.

**Comment by benjamin-albert** [comment]
I don't understand, do you mean Dillinger is preventing firefox from opening a new tab or are you expecting a new tab in Dillinger?

If you are expecting a new tab in Dillinger, we can consider this issue a feature request.

**Comment by avinoth** [comment]
@benjamin-albert I'm so sorry for the delayed response. It's an issue, Dillinger is preventing firefox to open a new tab. Instead the `ctrl + t` shortcut does letter swapping.

**Comment by benjamin-albert** [comment]
@avinoth What operating system are you experiencing this issue on?

**Comment by avinoth** [comment]
@benjamin-albert Ubuntu 14.04

**Comment by joemccann** [comment]
Can't reproduce.
