### ISSUE TITLE
failure to run locally on ubuntu 15.10

### ISSUE THREAD

**Issue by amioi** [joemccann/dillinger#523]
I am trying to take a copy of dillinger and run locally on ubuntu 15.10. It fails to run with below message and I double checked there is no change in the server.js file. It may look like a newbie question. Could anyone help to point out what might go wrong?

Thanks a lot.

============================================================================
```
~/dillinger$ sudo nodejs app

Dropbox config not found at /home/pac/dillinger/plugins/dropbox/dropbox-config.json. Plugin disabled.
Github config not found at /home/pac/dillinger/plugins/github/github-config.json. Plugin disabled.
Google Drive config not found at /home/pac/dillinger/plugins/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /home/pac/dillinger/plugins/onedrive/onedrive-config.json. Plugin disabled.

/home/pac/dillinger/plugins/core/server.js:92
    getPhantomSession().then(phantom => {
                                                                 ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pac/dillinger/app.js:23:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by benjamin-albert** [comment]
The server side JavaScript requires ES 6 support.

@amioi What version of node.js are using.

You can find this out by running:

    $ node --version

**Comment by amioi** [comment]
:~/dillinger$ node --version
v0.10.25

**Comment by amioi** [comment]
Tried with ES6 package, pity still same error message. Any hint most welcome =) 
`sudo apt-get install node-es6-shim`

**Comment by benjamin-albert** [comment]
node.js v0.10.25 doesn't seem to support ES 6 (even when ran with the `--harmony` flag).

dillinger.io is using node.js version 4.3.2.

Updating node.js should fix this issue.

**Comment by benjamin-albert** [comment]
I use [nvm](https://github.com/creationix/nvm) (or [nvm-windows](https://github.com/coreybutler/nvm-windows) when I'm stuck on windows) to conveniently switch between multiple node.js versions.

**Comment by benjamin-albert** [comment]
I just checked [ECMAScript 6 compatibility table](https://kangax.github.io/compat-table/es6/) and it looks like v4.0 is the minimum required node.js version for [arrow function ](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) support (which is the syntax node is complaining about).

**Comment by benjamin-albert** [comment]
I'm closing this issue now.

If you update to (at least node v4) and you're:
* Still getting the same syntax error then we can reopen this issue.
* Getting a different error then feel free to open another issue.

**Comment by benjamin-albert** [comment]
@joemccann I think it's a good idea to update the Readme with this requirement.

Stay tuned for a PR.

**Comment by amioi** [comment]
I confirm the issue is resolved after update Node.js (my case to v4.2.6).
-----------------------------

The local server now starts, but webpage hangs at "Prepping all the things". Terminal output as below:

```
$ sudo node app
Dropbox config not found at /home/pac/dillinger/plugins/dropbox/dropbox-config.json. Plugin disabled.
Github config not found at /home/pac/dillinger/plugins/github/github-config.json. Plugin disabled.
Google Drive config not found at /home/pac/dillinger/plugins/googledrive/googledrive-config.json. Plugin disabled.
OneDrive config not found at /home/pac/dillinger/plugins/onedrive/onedrive-config.json. Plugin disabled.
Express server listening on port 8080

http://undefined:8080

Evernote not implemented yet.
GET / 304 43.194 ms - -
GET /css/app.css 304 9.145 ms - -
GET /js/bundle.js 404 7.399 ms - 25
GET /img/icons/file.svg 304 0.984 ms - -
```

**Comment by benjamin-albert** [comment]
As stated in the [Installation](https://github.com/joemccann/dillinger#installation) section of the project's Readme you need to run:

```
gulp build --prod
$ NODE_ENV=production node app
```

Gulp produces the `/js/bundle.js` file from all the source files.

**Comment by amioi** [comment]
Thanks a lot for your kind help. I confirm this helps to solve the issue above.

**Comment by benjamin-albert** [comment]
@amioi You're welcome :)

**Comment by joemccann** [comment]
Agreed let's add to the README

**Comment by benjamin-albert** [comment]
@joemccann I added this requirement to the Readme, see #524

The PR was already merged, see the [Installation](https://github.com/joemccann/dillinger#installation) section to the Readme.
