### ISSUE TITLE
Empty table data tag doesn't render properly into html

### ISSUE THREAD

**Issue by matanh-tzmedical** [joemccann/dillinger#529]
Using dillinger.io.

A table with an empty first <td> tag will display the following <td> tag as first tag instead of the second.

Example, this markdown:

```
1  | 2
-- | --
   | 3
```

Will do this:

```
<tr>
  <td>3</td>
  <td></td>
</td>
```

Instead of:

```
<tr>
  <td></td>
  <td>3</td>
</td>
```

**Comment by joemccann** [comment]
This is bug with Ace Editor
