### ISSUE TITLE
Feature Request: Publish to Medium

### ISSUE THREAD

**Issue by rmelly** [joemccann/dillinger#532]
Would love to be able to publish directly to Medium from Dillinger. Medium just (Oct '15) released an API with Markdown support: https://medium.com/developers/welcome-to-the-medium-api-3418f956552.

Current options for posting .md files to Medium are very limited. They are mostly workarounds (https://medium.com/@andymcfee/how-to-import-markdown-into-medium-c06dc981bd96) that as of May '16 do not appear to still work.

**Comment by joemccann** [comment]
yup love this...should be able to mimic what we do with the other service
providers in `plugins`

**Comment by joemccann** [comment]
I'm currently work on a functioning prototype of this now. Stay tuned.

**Comment by joemccann** [comment]
This is now implemented.  Please file any bugs you may find.
