### ISSUE TITLE
[Feature Request]Preview PDF and HTML in browser

### ISSUE THREAD

**Issue by zh19970205** [joemccann/dillinger#540]
It would be convenient if dillinger can preview PDF or HTML in browser rather than download it directly.

**Comment by benjamin-albert** [comment]
@zh19970205 when you say preview HTML you mean just plain HTML because you already get an styled HTML preview on the right.

**Comment by zh19970205** [comment]
ehhhhh.. I mean preview HTML in another tabs ...
ctrl-S is easy
and if you use chrome,click "export as pdf", it download to default download folder directly. and i have to open explorer to move this file...

**Comment by benjamin-albert** [comment]
How about adding a PREVIEW AS menu which allows you to choose the format to preview in a new browser window/tab.

**Comment by zh19970205** [comment]
Yes, This is what I want to say, Sorry for my poor expression =_=

**Comment by benjamin-albert** [comment]
This sounds like a nice feature that is easy to implement.

Stay tuned for a pull request.

**Comment by joemccann** [comment]
this introduces a race condition with concurrent connections since the URL is not unique

http://localhost:8080/factory/fetch_html

This will potentially be different for the user depending on when they click it

**Comment by benjamin-albert** [comment]
@joemccann Non unique URLs are an implementation detail of #544 so lets continue this discuss over there.
