### ISSUE TITLE
[Feature Request] Save to existing dropbox folder

### ISSUE THREAD

**Issue by owainjohnstone** [joemccann/dillinger#545]
First, thanks for hosting such a great project.

It would be fantastic if I could save files to existing dropbox folders (rather than the 'Dillinger' folder). At the moment, importing from Dropbox then saving results in creating another copy of the file in the Dillinger folder - what I'd like is to save over the original copy in its existing folder to prevent duplication and maintain my folder structure. 

Any chance this is feasible?

**Comment by Dschaehn** [comment]
Agree, very nice project, but I miss this feature too! Would be great if I could keep my original folder structure in Dropbox.

**Comment by joemccann** [comment]
I had to make the decision to create a "Dillinger" folder in the root.  Adding the complexity of choosing your dropbox folder and then retaining its state across tens of thousands of users was challenging years ago when I wrote this app so I landed on keeping it consistent for everyone, across every provider.  If you can create an elegant solution I'm happy to review the pull request!
