### ISSUE TITLE
Can dillinger work without plugins ie (googledrive, dropbox ...)

### ISSUE THREAD

**Issue by cmsdesigner** [joemccann/dillinger#550]
Who can i  disable one off plugins when installing dillinger

**Comment by benjamin-albert** [comment]
If you clone the repo, build from source and run the server all plugins will be disabled (until you configure them).

You can also [download a pre-built version from my fork](https://github.com/benjamin-albert/dillinger/releases).

**Comment by benjamin-albert** [comment]
This issue has been inactive quite a while so I'm closing it.
