### ISSUE TITLE
No Repositories

### ISSUE THREAD

**Issue by ChappIO** [joemccann/dillinger#551]
Whenever I open up http://dillinger.io/ and I link with github I can see all my organizations, but when I open any organization (or my personal account) it does not list any repositories. Do I have to do something to activate repositories for dillinger?

**Comment by sklosedr** [comment]
we he the same error

**Comment by joemccann** [comment]
hmm weird this must be a regression

**Comment by joemccann** [comment]
I'm actually not getting this error...maybe unlink and relink github?

**Comment by thomasbiesaart** [comment]
Nope, still the same thing. I remove the OAuth from my account and logged in again.

I can see the organizations but not repositories.

![image](https://cloud.githubusercontent.com/assets/13708940/16712088/3dfeece6-467b-11e6-87bb-0641e758bd97.png)

**Comment by benjamin-albert** [comment]
I'm not having this issue either.

@thomasbiesaart Can you tell us the exact steps you are taking to reproduce this problem.

For example I see you are part of an organization on GitHub, are you trying to see the Organizations repos to your own repos.

Are you authorizing public only repos or public **and private** repos?

**Comment by thomasbiesaart** [comment]
Here are my steps:

![image](https://cloud.githubusercontent.com/assets/13708940/16713777/0e6039cc-46b2-11e6-8580-c4a54644a301.png)
![image](https://cloud.githubusercontent.com/assets/13708940/16713779/180b5402-46b2-11e6-9933-8a150b9e199a.png)
![image](https://cloud.githubusercontent.com/assets/13708940/16713783/309eb19e-46b2-11e6-9e85-5f71f0974a02.png)
![image](https://cloud.githubusercontent.com/assets/13708940/16713784/34bb12ae-46b2-11e6-9247-f1844bb23900.png)
![image](https://cloud.githubusercontent.com/assets/13708940/16713786/37d8e38a-46b2-11e6-9839-91984fe798f0.png)


It might be good to note that my account is secured using 2-factor authentication.

**Comment by joemccann** [comment]
that may be the culprit...2FA...I don't have it enabled

**Comment by benjamin-albert** [comment]
I don't understand how 2FA causes a problem here if we're using OAuth.

The whole point of OAuth is that we get a token back from GitHub which is supposed to hide the real authentication method the user is using.

@joemccann Can you explain to me why 2FA is causing the problem?

**Comment by joemccann** [comment]
I'm not declaring it _is_ the issue -- I'm saying that it is the only
variable in our setups

**Comment by snrmwg** [comment]
Same issue here and I do not have enabled 2FA in Github. Want to edit file from my own public repository. Tried it with both access levels (public only / private and public).

**Comment by snrmwg** [comment]
Maybe the cause are _to few repositories_? :-)

I get an `d.pagination is null` error after the POST to `/import/github/repos`:

![auswahl_002](https://cloud.githubusercontent.com/assets/1194737/17077505/a3956448-50d2-11e6-87a5-ebee63b43b21.png)

**Comment by snrmwg** [comment]
Can someone tell me please how I can develop client side javascript in this project? How do I rebuild the /js/bundle.js?

**Comment by joemccann** [comment]
Marc,

Check the README.md -- the installation steps are there but specifically

`npm run predeploy`

this will rebuild the bundle but be sure to npm install everything

**Comment by slimelia** [comment]
I'm also experiencing this issue and I do not have 2FA on GitHub.

**Comment by graredcr** [comment]
I have the same problem,, and a track for fix it.

The app get the repositories but I thing without the expected format.
Lock the screens:

Get the organization ok:

![captura de pantalla 2016-08-25 a las 12 47 26](https://cloud.githubusercontent.com/assets/1648964/17966634/d937ee4a-6ac2-11e6-89dc-2c37e709e903.png)

The json its ok.

But the repos:
![captura de pantalla 2016-08-25 a las 12 49 43](https://cloud.githubusercontent.com/assets/1648964/17966640/deeb4bac-6ac2-11e6-823f-155eec83f698.png)


With a diferent json, but the repos are here. It's the javascript the problem?

Cristian

**Comment by graredcr** [comment]
Posible solution:

https://github.com/graredcr/dillinger/commit/1fe2d85268ded4667bbebc8aaf00187c47962ad4

**Comment by joemccann** [comment]
pull request to master!

**Comment by joemccann** [comment]
@graredcr any chance you can submit a PR?

**Comment by graredcr** [comment]
How? @joemccann I belived that was a master work. How I can make this?

**Comment by joemccann** [comment]
you have your fork, correct?

Just submit a Pull Request on this account (joemccann/dillinger) with the
code you used to fix your fork.

**Comment by joemccann** [comment]
I believe this is resolved.
