### ISSUE TITLE
What libraries should we use to write new test?

### ISSUE THREAD

**Issue by benjamin-albert** [joemccann/dillinger#553]
I want to write some tests for the preview directive and I want to know if you think we should continue use ing [Jasmine](https://github.com/jasmine/jasmine) or should all our new test be written using [tape](https://github.com/substack/tape)? 

I insist on using [tape](https://github.com/substack/tape) to write some test for the server side document export code.

I've been using [tape](https://github.com/substack/tape) in a new work project, and I really like it.

@joemccann What do you think?

**Comment by joemccann** [comment]
Tape

On Tuesday, June 28, 2016, Benjamin Albert <notifications@github.com> wrote:

> I want to write some tests for the preview directive and I want to know if
> you think we should continue use ing Jasmine
> <https://github.com/jasmine/jasmine> or should all our new test be
> written using tape <https://github.com/substack/tape>?
>
> I insist on using tape <https://github.com/substack/tape> to write some
> test for the server side document export code.
>
> I've been using tape <https://github.com/substack/tape> in a new work
> project, and I really like it.
>
> @joemccann <https://github.com/joemccann> What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joemccann/dillinger/issues/553>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAC8agwZAQbu5-Wrotjq6sMVYR0U9qgdks5qQVThgaJpZM4JAUml>
> .
>


-- 
Sent from Joe In Real Life

**Comment by benjamin-albert** [comment]
Great, I'll use tape.
