### ISSUE TITLE
How to create an access from other computer 

### ISSUE THREAD

**Issue by monsieurpouet** [joemccann/dillinger#560]
Hi !
So, why 127.0.0.1:8000 ?
How to change that ?

**Comment by benjamin-albert** [comment]
Dillinger's port defaults to `8080`.
You can change it by setting the `PORT` environment variable.

Unix example:

    PORT=80 node app

Windows example:

    set PORT=80 node app

**Comment by monsieurpouet** [comment]
w0nderfu|| :)
Thx !
