### ISSUE TITLE
Navigation with keyboard arrows and home/end not working afters switching language with win+space

### ISSUE THREAD

**Issue by saitonakamura** [joemccann/dillinger#572]
When I switch languages using win+space keyboard navigation (arrows, home, end) stop working until I switch the active tab or the entire window
I'm using online dillinger from [http://dillinger.io/](http://dillinger.io/) under `Windows 10`, `Chrome 53.0.2785.116 m (64-bit)`

**Comment by joemccann** [comment]
probably an issue with keyboard.js

**Comment by saitonakamura** [comment]
Thanks, I will check it out

**Comment by joemccann** [comment]
@saitonakamura any luck?

**Comment by saitonakamura** [comment]
@joemccann sorry, didn't have time (or enough will) to check
I'll close the issue for now and reopen it if needed
