### ISSUE TITLE
End word charecters visible in chrome

### ISSUE THREAD

**Issue by Gedminiux** [joemccann/dillinger#574]
![image](https://cloud.githubusercontent.com/assets/3483449/19236265/1206786c-8eff-11e6-9257-6909e83aca3a.png)

using google-chrome-stable (Google Chrome 51.0.2704.84 ) and ArchLinux.

the characters are added automatically and interfere with the location of the cursor in the editor.

Do not have problems in Firefox

Same things can be reproduced under localhost

When copied the string and analysed under HEX I could not seem to find them.

EDIT:
#569 seems to be the exact issue. Sorry for the duplicate. I'll let you know if updating chrome resolved the issue.

EDIT2:
it did not resolve updating the chrome to - Google Chrome 53.0.2785.143

**Comment by joemccann** [comment]
update chrome...some logged this bug a while back...it's a bug in chrome

**Comment by Gedminiux** [comment]
okay, this is strange.

The person at #569  had this issue fixed with v 52.0.2743.116

I am using
Google Chrome 53.0.2785.143 

and It's back up again. I don't want to roll back. Any other suggestions?

**Comment by joemccann** [comment]
very bizarre...no idea why it would come back

I'm running Version 53.0.2785.143 (64-bit) on my Mac and don't have that
issue??
