### ISSUE TITLE
Can't include an image from Google drive with a shared link

### ISSUE THREAD

**Issue by scrumit** [joemccann/dillinger#579]
I have tried to include a PNG or JPG image from google drive by creating a shared link. 

I think, because of the format of the link the parser may not understand the type of the image so it is not being displayed.

Here is an example image link.

https://drive.google.com/open?id=0B1mjaCOsAMatM3JyY3doVXdsY1E

**Comment by joemccann** [comment]
yeah the problem is that link resolves to an actual webpage, a "viewer" of
the image itself.

Here's the direct link to the *actual* image:

https://lh3.googleusercontent.com/A-U0RhhlnTIYKQqKXmhjv7ebXX5UQmZX2TAOAmrfTeDkuox9xcbfXMqX-JH2oJ-riFilzU6kW-WfjBI=w1362-h604-rw

**Comment by scrumit** [comment]
Got it. On the shared viewer screen I select copy link address from context menu.  Your image link fails for me, so the file migrates around Amazon's CDN.  To me (in another continent) it is on:

https://lh5.googleusercontent.com/zXXg1GusIpPWpUb14zmjKUTyIAROh5BIqvyuZCDj5VPtvOSA7NPt9GEVXVmaEeYPNEt8ygFeund6YQs=w1344-h652-rw

Still, it's solved that problem. Perhaps something to go into the documentation?
