### ISSUE TITLE
[Bug] SyntaxError: missing = in const declaration on FF49

### ISSUE THREAD

**Issue by hansvn** [joemccann/dillinger#582]
On FireFox 49.0.2 The editor is stuck loading on the 'Prepping all the things...' screen.

The error inspector gives the following error:
```js
SyntaxError: missing = in const declaration
http://dillinger.io/js/bundle.js
Line 115190

for (const currentValue of input) {
```

I saw that this was changed in the last commit (98aec229b3a561a41e73a64ba779c0a050477348).

No issues on Chrome btw.

**Comment by joemccann** [comment]
yeah this bug keeps creeping back up with punycode.js  -- i'll try to fix
now

**Comment by joemccann** [comment]
Fixed!
