### ISSUE TITLE
[Feature Request] Bulk Export

### ISSUE THREAD

**Issue by jnschrag** [joemccann/dillinger#583]
I think it would be really useful to be able to bulk export files instead of having to open them individually first. The current process to export isn't difficult (or all that time consuming), but if you have a lot of files to export, it can get pretty tedious very quickly.

Thanks for the excellent app!

**Comment by joemccann** [comment]
So you want to export as markdown, pdf, html and styled html in a zip file?

**Comment by jnschrag** [comment]
@joemccann No, sorry, I wasn't clear.

I meant if I had 10 documents, it would be nice to be able to export them to whatever format in bulk. So if I select all 10 documents, choose export to HTML, I would get a zip file of the 10 documents as HTML files.

**Comment by joemccann** [comment]
Hmm that's not really what dillinger does but in essence you want the
ability to say drag 10 markdown files into dillinger and then have them all
be exported as HTML?

**Comment by jnschrag** [comment]
Yep, or even just being able to export all of the documents in the current session at the same time.

**Comment by joemccann** [comment]
sounds like a userscript or greasemonkey script is something you could do
in the interim

**Comment by joemccann** [comment]
Did you make any progress on this?

**Comment by jnschrag** [comment]
I ended up using a different markdown editor that met my needs better. Feel free to close this issue (although I still think it would be  useful feature if it fits in the scope of the project).
