### ISSUE TITLE
[Feature Reqeust] Change tab size

### ISSUE THREAD

**Issue by ha404** [joemccann/dillinger#584]
Allow option for configuring tab size (2 spaces, 4 spaces, etc.)

**Comment by joemccann** [comment]
where in the UI?

**Comment by hawsome** [comment]
I'm thinking somewhere in this menu:
<img width="321" alt="screen shot 2016-11-14 at 9 01 26 am" src="https://cloud.githubusercontent.com/assets/567126/20274311/fd3b067c-aa48-11e6-8b5c-e7993630c771.png">

**Comment by joemccann** [comment]
I'm happy to review a Pull Request if you'd like to add it.  Seems like a straightforward addition to the ace editor configuration.

**Comment by joemccann** [comment]
`editor.getSession().setTabSize(2);`

https://ace.c9.io/#nav=howto

**Comment by joemccann** [comment]
@ha404 did you ever work on this?

**Comment by dwaq** [comment]
This issue can be closed now.
