### ISSUE TITLE
Accented letters aren't being displayed correctly

### ISSUE THREAD

**Issue by matheusmariano** [joemccann/dillinger#585]
Hey, there.

I'm in trouble with accented letters. On MacBook, with EUA keyboard, when I press `´ + a` (option + e + a), it normally returns `á`, but Dillinger is actually returning `´áa` .

How can we fix that? :D

**Comment by joemccann** [comment]
hmm maybe a bug in the Ace Editor?

**Comment by matheusmariano** [comment]
Yes. I figured out it happens in other Ace editors. This issue already was reported here: https://github.com/ajaxorg/ace/issues/3138.
