### ISSUE TITLE
[Feature Reqeust] Add BitBucket support

### ISSUE THREAD

**Issue by batandwa** [joemccann/dillinger#586]
Add BitBucket for importing and exporting documents.

Besides the obvious selfish reasons :grin:, I think BitBucket is popular enough to warrant some attention.

**Comment by joemccann** [comment]
Have a go at it and submit a PR!

**Comment by june07** [comment]
https://github.com/joemccann/dillinger/pull/603

**Comment by joemccann** [comment]
Done!
