### ISSUE TITLE
Sync don't work properly, when document have big tables

### ISSUE THREAD

**Issue by LeonisX** [joemccann/dillinger#587]
I take this opportunity to thank you for the work.
Example file: https://github.com/LeonisX/game-commander/blob/master/docs/TOSEC%20naming%20convention.md

**Comment by joemccann** [comment]
Not sure what the issue is. I copy/pasted your markdown into dillinger.io
and didn't have any issues.

**Comment by LeonisX** [comment]
I have tested on Ubuntu 16.04: Firefox, Chromium, Default browser.
Please, look at lines 270 and below - mistiming more than half a page. This inconvenienceю

**Comment by joemccann** [comment]
Can you take a screenshot please?

**Comment by LeonisX** [comment]
I've got a little more information about the problem. If you scroll through the text from start to finish, it becomes clear that all is well with scrolling. At the beginning and at the end the excellent synchronization. But in the middle, under the condition that the document has many tables, synchronization is disturbed. I did not see the code, because poorly versed in JS, but the behavior of the windows, I can say that the sliders are moved synchronously, for example, if 50% of the left, the right and also 50%. But in fact, the information, especially if you have tables that are very heterogeneous, where the table - the density is lower, because of this happens out of synchronization. The only solution - synchronized by tags or content of the text.

OK:
![2016-11-24 21-35-01](https://cloud.githubusercontent.com/assets/13258944/20608849/aa129c70-b296-11e6-9f3c-01b40d62db8e.png)
OK:
![2016-11-24 21-35-23](https://cloud.githubusercontent.com/assets/13258944/20608852/aa140e02-b296-11e6-96bb-821a7a21b495.png)
NOT:
![2016-11-24 21-35-40](https://cloud.githubusercontent.com/assets/13258944/20608850/aa132758-b296-11e6-804e-22720cee83d0.png)
NOT:
![2016-11-24 21-35-48](https://cloud.githubusercontent.com/assets/13258944/20608851/aa139184-b296-11e6-8723-6bc740a46b95.png)
OK:
![2016-11-24 21-37-28](https://cloud.githubusercontent.com/assets/13258944/20608995/51b8c412-b298-11e6-9ec9-b7c614fd5b4d.png)

**Comment by joemccann** [comment]
This is part of the issue with scroll sync. We need the scroll sync to
match the rendered tags not just the html text itself

**Comment by joemccann** [comment]
If you'd like to attempt to improve the scroll sync, please let me know!  It is a bad bug indeed.
