### ISSUE TITLE
Incorrect encoding, when import file from GitHub

### ISSUE THREAD

**Issue by LeonisX** [joemccann/dillinger#588]
I have document in Russian: https://github.com/LeonisX/game-commander/blob/master/docs/TOSEC%20naming%20convention.md

When I copy/paste text in editor - all OK, when import from file - OK too. But when I import this file from GitHub - all Russian symbols are corrupted.

**Comment by joemccann** [comment]
Appears to be a formatting issue.

Have you looked at the import source code for GitHub in the
`plugins/github` directory?

**Comment by joemccann** [comment]
https://github.com/joemccann/dillinger/blob/master/plugins/github/github.js#L319

Maybe this?

**Comment by LeonisX** [comment]
May be, I use UTF-8.

Sorry, can't test this locally, have these issue:

`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm info ok `

Dillinger launch locally, but I can't see any services in right menu

**Comment by benjamin-albert** [comment]
You need to configure the GitHub plugin.

https://github.com/joemccann/dillinger/blob/master/plugins/github/README.md

**Comment by LeonisX** [comment]
Thanks. Done. All work. #589

**Comment by joemccann** [comment]
Fixed!
