### ISSUE TITLE
Not a real native browser editor

### ISSUE THREAD

**Issue by PhiLhoSoft** [joemccann/dillinger#590]
Not sure what title to put...
I tried shortly Dillinger, pasting a Markdown text I was editing in Atom. The rendering was nice, but I quickly discovered something odd about the editor.
First, there is no spellchecking. The reason I went to an online editor was the ability to leverage the spellchecking ability of the browser, here Chrome on Windows 10. I play with the Chrome settings, setting the language, etc., but no spellchecking there.
Second, there is no management of the move keys. I press up arrow, the caret goes beyond the top of the text area... and becomes hidden! No automatic scroll there. Page up and Page down keys are just seemingly ignored. Idem for Ctrl+Home and Ctrl+End. The caret moves as expected, but just goes beyond the viewport.
I fear I have to search something simpler and more effective... Thanks for sharing, anyway, keep up the efforts! 😄

**Comment by joemccann** [comment]
This is not an issue with Dillinger but is a limitation of the Ace Editor
which is a Dillinger dependency.

https://github.com/ajaxorg/ace/issues/2107

**Comment by PhiLhoSoft** [comment]
OK, thanks for the link, I will vote on the Ace issue, then. I close this issue.
