### ISSUE TITLE
"Callback URL" in dropbox config unclear

### ISSUE THREAD

**Issue by pokrface** [joemccann/dillinger#592]
I am uncertain what to supply for the `callback_url` variable in dillinger's dropbox configuration. The readme does not explain what it is or what it does, and Dropbox's developer documentation isn't helping me.

Do I just need to put the URL for my dillinger site? I've tried that, but the dropbox link never completes—it appears to complete, but the link icon isn't highlighted. I can see stuff happening in the log, but I'm not sure what I *should* be seeing.

Here's the log output from when I try to link:
```
::ffff:10.10.10.110 - GET /?oauth_token=redacted&uid=redacted HTTP/1.1 200 - - 17.094 ms
::ffff:10.10.10.110 - GET /css/app.css HTTP/1.1 200 - - 5.995 ms
::ffff:10.10.10.110 - GET /img/icons/file.svg HTTP/1.1 200 - - 2.120 ms
::ffff:10.10.10.110 - GET /js/bundle.js HTTP/1.1 200 - - 2.882 ms
::ffff:10.10.10.110 - GET /img/icons/enter-zen.svg HTTP/1.1 200 - - 1.789 ms
https://www.dropbox.com/1/oauth/authorize?oauth_token=redacted&oauth_callback=http://dillinger.bigdinosaur.lan:8080 is the auth_url for dropbox
::ffff:10.10.10.110 - GET /redirect/dropbox HTTP/1.1 302 298 - 280.817 ms
Evernote not implemented yet.
::ffff:10.10.10.110 - GET /?oauth_token=redacted&uid=redacted HTTP/1.1 200 - - 2.677 ms
::ffff:10.10.10.110 - GET /css/app.css HTTP/1.1 304 - - 2.509 ms
::ffff:10.10.10.110 - GET /js/bundle.js HTTP/1.1 304 - - 2.127 ms
::ffff:10.10.10.110 - GET /img/icons/file.svg HTTP/1.1 304 - - 0.565 ms
::ffff:10.10.10.110 - GET /img/icons/enter-zen.svg HTTP/1.1 304 - - 0.621 ms
```

Any assistance would be appreciated.

**Comment by joemccann** [comment]
For Dillinger.io, the callback URL is

http://dillinger.io/oauth/dropbox

Check that route

**Comment by pokrface** [comment]
Thank you—using `http://myurl/oauth/dropbox` in the callback URL worked perfectly!

Suggestion: it might be helpful to mention this in the readme for the Dropbox plugin.

**Comment by joemccann** [comment]
Would you mind adding to the Dropbox readme and submitting a pull request?

**Comment by pokrface** [comment]
Done!

**Comment by joemccann** [comment]
awesome thanks!
