### ISSUE TITLE
Behaviour of Ctrl-left/right and Ctrl-backspace/delete - sticking to space boundaries

### ISSUE THREAD

**Issue by fractos** [joemccann/dillinger#594]
The behaviour of Ctrl-left, Ctrl-right, Ctrl-backspace/delete is fundamentally different to every other editor I can think of in that it will pause for the space characters in between words and require an extra press to move to the next word's boundary. For instance, in both Visual Studio and Notepad++, Ctrl-backspace favours the beginning of a word, so that repeated presses will delete characters up to and including the first character of the previous word. Ctrl-left/right will do the same, moving to the first character of a word.

Having a different behaviour in dillinger provides a certain amount of cognitive dissonance. Is it possible for this to be controlled by a sticky option in the user interface?

**Comment by joemccann** [comment]
Likely an Ace Editor issue which is what Dilliger depends upon.

**Comment by fractos** [comment]
Looks like a couple of items on their github in this area:

https://github.com/ajaxorg/ace/issues/2296
https://github.com/ajaxorg/ace/issues/2257 - (this might be a workaround)

**Comment by joemccann** [comment]
Also, not seeing this isse on macOS.  Are you on windows?

**Comment by fractos** [comment]
Hi, yes sorry, I forgot to mention that.

**Comment by joemccann** [comment]
Ok gotcha. I'm not on a Windows machine and do not have that issue when holding down Option+Arrow Left/Right :(

**Comment by fractos** [comment]
sigh
