### ISSUE TITLE
Save to disk seems broken / not possible

### ISSUE THREAD

**Issue by bergtwvd** [joemccann/dillinger#596]
Using joemccann/dillinger:3.12.0.

I can do Import From > FIle on Disc
But Save To does not show anything.

**Comment by joemccann** [comment]
This is for importing not saving

**Comment by bergtwvd** [comment]
I had the impression that the Save To was part of it.
In that case, any plans of adding this in?

**Comment by joemccann** [comment]
Save to Disk is actually just "Export as Markdown".  This saves it by
downloading the file to your downloads folder.
