### ISSUE TITLE
website dillinger.io is down?

### ISSUE THREAD

**Issue by mallim** [joemccann/dillinger#597]
http://dillinger.io/ is forever loading

**Comment by joemccann** [comment]
You're right I have no idea what's going on. No changes is weeks. I'll
check the Google Cloud logs

**Comment by joemccann** [comment]
Backup. Looks like a GCP issue.

**Comment by andyttran** [comment]
It looks like [dillinger.io](http://dillinger.io) is down again.

**Comment by joemccann** [comment]
Must be something on GCP. I'll try to fix from my phone now

Havent pushed any changes in days

**Comment by andyttran** [comment]
Thanks Joe! back up and running.

**Comment by JonathanSpeek** [comment]
It looks like dillinger.io is down again?

**Comment by qm3ster** [comment]
Hello. Down for me right now.

**Comment by joemccann** [comment]
Still a kubernetes bug...no idea what the issue is. sorry!

On Sun, Apr 2, 2017 at 7:31 AM, Mihal Malostanidis <notifications@github.com
