### ISSUE TITLE
package.json error

### ISSUE THREAD

**Issue by shuntera** [joemccann/dillinger#600]
I get this error at the end after attempting to build Dockerfile

```
Setting up python-software-properties (0.92.37.7) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
 ---> d255a210d1bf
Removing intermediate container 253ebca7f38e
Step 4 : COPY package.json ./package.json
lstat package.json: no such file or directory
```

**Comment by joemccann** [comment]
Hmm, that's odd.  I haven't seen this...what OS are you on?

**Comment by shuntera** [comment]
I'm on macOS Sierra 10.12.2

**Comment by joemccann** [comment]
Not having an issue locally.  Are you sure you are running from the root
directory?

**Comment by joemccann** [comment]
I was able to build from scratch

![image](https://cloud.githubusercontent.com/assets/48234/22600298/be055c56-e9ee-11e6-886b-f6e052746ce4.png)
