### ISSUE TITLE
redirect_uri

### ISSUE THREAD

**Issue by jonygli** [joemccann/dillinger#611]
according to [onedrive/README.md](https://github.com/joemccann/dillinger/blob/master/plugins/onedrive/README.md), I tried to set up it to use onedrive. however, what is 'redirect_uri'?

if dillinger is launched at http://mydillinger.host.net:8080, what should I set for redirect_uri?

**Comment by qbunt** [comment]
Based on how other OAUTH implementations work, it looks like it'd be:
http://mydillinger.host.net:8080/oauth/onedrive
Hope that works!

**Comment by jonygli** [comment]
thanks, however, it reported the following error"
https://login.live.com/oauth20_desktop.srf?error=invalid_request&error_description=The provided value for the input parameter 'redirect_uri' is not valid. The client application must be marked as 'mobile', or the value must be an absolute URL which matches the registered redirect URI.&lc=1033", 

and, don't if it is because I had not config 'Redirect URLs' in the 'Live SDK app management site' as I can't find where to config it.
