### ISSUE TITLE
is dillinger.io down?

### ISSUE THREAD

**Issue by yashasvigirdhar** [joemccann/dillinger#615]
Not able to open the site. Seems like it's timing out.

Browser : 

Google chrome 
version 57.0.2987.110

**Comment by joemccann** [comment]
yeah this is a known issue with the kubernetes cluster I have on Google
cloud

**Comment by firasm** [comment]
FYI: The site is down again:

<img width="824" alt="Screen Shot 2020-01-23 at 11 06 57 AM" src="https://user-images.githubusercontent.com/2507459/73015279-932e5300-3dd0-11ea-91f7-485a35a6151e.png">

https://downforeveryoneorjustme.com/dillinger.io

**Comment by joemccann** [comment]
Hmm not sure what happened as it is up for me
