### ISSUE TITLE
Can't import from dropbox

### ISSUE THREAD

**Issue by ladz** [joemccann/dillinger#616]
macOS Sierra Version 10.2.3
Chrome Version 57.0.2987.133 (64-bit)

I successfully connected dillinger to my dropbox- however, when I click 'IMPORT FROM > DROPBOX' the 'Fetching Markdown related files from Dropbox..' hint appears but nothing happens. 
<img width="869" alt="screen shot 2017-04-06 at 10 11 13" src="https://cloud.githubusercontent.com/assets/1828795/24744287/cd408b34-1ab1-11e7-86da-aa233a5ccac6.png">

**Comment by joemccann** [comment]
Not sure what happened with the latest build but google drive and dropbox are both broken. This is a bug

**Comment by joemccann** [comment]
all tests were passing

**Comment by ladz** [comment]
console logs in firefox:
<img width="836" alt="screenshot 2017-04-07 09 28 53" src="https://cloud.githubusercontent.com/assets/1828795/24789834/db304d10-1b74-11e7-8913-e4f92050d1c6.png">

**Comment by joemccann** [comment]
omg finally tracked it down.  

https://docs.angularjs.org/api/ng/service/$http

The `.success()` and `.error()` promises abstractsion in Angular 1.3 have broken the app.  They are deprecated as of 1.6 but it doesn't explain why they are breaking now unless there is a browser-implementation change.

I'll be having to patch every single plugin that uses this abstraction.

**Comment by joemccann** [comment]
Ok patched all for Dropbox. Deploying now. Sincere apologies for the issue!

**Comment by joemccann** [comment]
Ok this is working. Give it a go and file any issues.
