### ISSUE TITLE
Forced Monospace Breaks Emoji

### ISSUE THREAD

**Issue by bnb** [joemccann/dillinger#624]
Been using Dillinger to write some stuff that has emoji in it today, and noticed that the cursor keeps getting put in the middle of the emoji. I kept having this problem in Slack, which is why I moved to Dillinger 😅.

That said, I figured out that it seems to be the forced monospace font that's causing this problem. My system is interpreting the emoji as the system versions of Emoji, but Dillinger is "forcing" them into the monospace font and font-width.

**Comment by joemccann** [comment]
Interesting.  Likely and Ace Editor setting or issue

**Comment by joemccann** [comment]
Yeah, this is an issue with Ace Editor. We'd have to create a custom renderer which seems like overkill.
