### ISSUE TITLE
Auto scroll on bounds

### ISSUE THREAD

**Issue by jmtt89** [joemccann/dillinger#632]
In Chrome 64 and Firefox for Linux, when reach bottom of the window the pointer just disappear, don't scroll down =(

**Comment by joemccann** [comment]
hmm weird...can you screen capture this bug

**Comment by clockworkgeek** [comment]
It does scroll when you type, just not when navigating with keys.

**Comment by joemccann** [comment]
Yeah unfortunately this is the way Ace Editor works within the CSS.
