### ISSUE TITLE
Dillinger.io site is down

### ISSUE THREAD

**Issue by GoCyberEd** [joemccann/dillinger#634]
Been working intermittently for me over the past week. Looks like it's down completely now. http://www.isitdownrightnow.com/dillinger.io.html

I love the service, and the alternatives can't come close. Any ETA on when it'll be back online?

Thanks!

![image](https://user-images.githubusercontent.com/4015651/29040177-0c3a6640-7b7c-11e7-8544-1884be0ea24a.png)

**Comment by joemccann** [comment]
The stangest thing.  There is nothing in the logs and all the dashboards on GCP and N|Solid show all instances and the instace group up and running.  Maybe a DNS issue but nothing has changed there either.

**Comment by joemccann** [comment]
back up...absolutely zero logs on what happened.  1 of the pods was completely missing in the Kubernetes cluster with no trace of what happened to it. Sorry!

**Comment by GoCyberEd** [comment]
No problem, thanks for the fast response! 

[Uptime robot](https://uptimerobot.com/) works well for monitoring a site for free, if your internal dashboards are bugging out.

**Comment by joemccann** [comment]
great thx
