### ISSUE TITLE
Configuration for docker

### ISSUE THREAD

**Issue by Jan0707** [joemccann/dillinger#639]
Hey folks,

Where does Dillinger keep it's data stored ? What dir should be mounted outside the docker container for better persistence across container tear downs ?

Best regards!

**Comment by joemccann** [comment]
Well, it doesn't really store any data except for the `/configs/` directory, assuming you are configuring the cloud providers or various plugins.

The idea is that the data is stored on Dropbox, Google Drive, etc.
