### ISSUE TITLE
issue abount input chinese

### ISSUE THREAD

**Issue by yy8623977** [joemccann/dillinger#641]
when you use the input method to enter chinese,you press botton 1 to select it,then you have to press 1 the second time,last the word is entered,but it display what you want input and number 1,it should press 1 only once

**Comment by kungming2** [comment]
Also experiencing this issue.

**Comment by joemccann** [comment]
Is this an Ace Editor issue?  Dillinger uses the Ace Editor.

**Comment by kungming2** [comment]
Doesn't seem to be an Ace Editor issue. I tried typing some Chinese at [the site](https://ace.c9.io/) and it worked fine, but not in Dillinger. Love Dillinger though!

**Comment by joemccann** [comment]
Maybe I need to update the Ace Editor package in `package.json`?

**Comment by joemccann** [comment]
I believe this is now fixed. @kungming2 can you confirm?

**Comment by kungming2** [comment]
@joemccann I can confirm that it works now! Thank you!
