### ISSUE TITLE
Error 401 when trying to save to Google Drive

### ISSUE THREAD

**Issue by vsajip** [joemccann/dillinger#659]
Perhaps analogous to #653. When I try to link to or save to Google Drive, I get an error:

![Image showing error message](https://i.imgur.com/tvWI7wJ.png)

This feature used to work fine.

**Comment by joemccann** [comment]
hmm wtf...nothing has changed so not sure why that happened

**Comment by joemccann** [comment]
I know what happened. The instanced got deleted by accident and I'm
attempting to restore it.  Please be patient!

**Comment by joemccann** [comment]
Fixed!

**Comment by vsajip** [comment]
That's stellar speed, thanks! And thanks very much, moreover, for Dillinger!

**Comment by joemccann** [comment]
you bet
