### ISSUE TITLE
Ctrl+S in "ace editor" will invoke browser's "Save as"

### ISSUE THREAD

**Issue by frank-fan** [joemccann/dillinger#66]
As descripted in title, when focus in 'ace editor' and press "Ctrl + s" will invoke the browser's "Save as" function, this make me realy crazy.

I see dillinger support "Ctrl + S" when you out of editor (because of key master), I suppose this may be a bug.

Acturely, I look up for how to solve it. Ace editor does provide a key command binding solution: 

``` js
editor.commands.addCommand({
name: 'saveFile',
bindKey: {
win: 'Ctrl-S',
mac: 'Command-S',
sender: 'editor|cli'
},
exec: function(env, args, request) {
alert("HI!");
}
});
```

Please fix it.

**Comment by nerdburn** [comment]
Perfect! Just what I needed, thank you.

**Comment by n5ken** [comment]
I use the code above but it does not works in latest Firefox, it's okay in Chrome.
