### ISSUE TITLE
dropbox import/export plugin

### ISSUE THREAD

**Issue by ScrumpyJack** [joemccann/dillinger#661]
Dropbox plugin fails with "missing client ID" (both on self-hosted and dillinger.io)

**Comment by joemccann** [comment]
No, you have to follow the instructions in each plugin folder where you
have to create your own API keys.l

**Comment by itsmehemant123** [comment]
I'm facing the same issue - this is where its happening: 
```javascript
{ '{"error": "v1_retired"}': '',
  authorize_url: 'https://www.dropbox.com/1/oauth/authorize?oauth_token=undefined' }
```

I see that there is a reference to the v1 api in https://github.com/joemccann/dillinger/blob/master/plugins/dropbox/dropbox.js#L37

I haven't spent time going through where else there might be references to the v1 api though.

**Comment by itsmehemant123** [comment]
Aight, so the `dbox` lib version in the package.json is the latest on npm, which is https://github.com/sintaxi/dbo. The author mentions that it is obsolete, so I guess you'd have to switch the dropbox library.

**Comment by joemccann** [comment]
Indeed.  All of dropbox has to be re-written.  I'll gladly pay someone $250
to do it.  I simply don't have the time!  There's new oauth flow that is
the main part that has to be fixed.
