### ISSUE TITLE
Overwrite files on Google Drive

### ISSUE THREAD

**Issue by adefelicibus** [joemccann/dillinger#664]
I've linked Dilinger with GD, created a file, saved as Filename.md and clicked on "Save to Google Drive".
When I go to my GD account, I see the file Filename.md.

However, If I change the file on Dilinger, it does not save the editions to GD.
If I click on "Save to Google Drive" again, Dilinger creates a new file.

Is it normal or I'm doing something wrong?

**Comment by joemccann** [comment]
Hmm that sounds like a bug. It shouldn't create a new file.

**Comment by js-kyle** [comment]
PR submitted for this issue
