### ISSUE TITLE
I WILL PAY YOU MONEY...Seriously 

### ISSUE THREAD

**Issue by joemccann** [joemccann/dillinger#668]
:moneybag::moneybag::moneybag:

Hey, it's me, @joemccann, author of Dillinger.  

The Dropbox plugin has been broken for a while and I have had no time to update it to the latest version of their API.  The Oauth piece is why it is broken.

It is likely the case that many of the API calls need to be updated, but it may just be the authorization part.  IDK because I haven't had time to work on it!

Nonetheless, I'm willing to pay _you_, yes _you_ to rewrite and fix this issue.

Please @ me here and let me know if you'd be interested.  Or email me directly at: 

joe@subprint.com

Bonus:  If you upgrade the entire app to the latest version of Angular or completely rewrite it for React I will pay you even more.

Happy to pay you in BTC, LTC or ETH as well.  Otherwise, expect U.S. Dollars.

Thanks!

**Comment by js-kyle** [comment]
@joemccann I've flicked you through an email

**Comment by valioDOTch** [comment]
Just a suggestion for next time
https://opencollective.com/learn-more

**Comment by httpete-ire** [comment]
@joemccann Tonic looks really interesting. 

A few concerns I have with using it
* using an experimental library (as stated on the website)
* alienating potential contributors
* performance on a large scale application
* removing the huge ecosystem of components available to react
 
I also think with the async/suspense features of React will help this kind of project greatly

**Comment by joemccann** [comment]
Good points.  I'm all for a React version too!
