### ISSUE TITLE
Request: Bookmarklet support

### ISSUE THREAD

**Issue by quantuminati** [joemccann/dillinger#669]
Great Editor! I would like to be able to include bookmarklets and was having an issue.

Or please let me know if I'm making an error. It appears I have to add an "h" at the front of the javascript string to get bookmarklets to "work" but then the user has to manually delete the "h" for it to operate after dragging to the bookmark bar.

What I tried -

[Bookmarklet Attempt 1][1js]
[Bookmarklet Hack 1][2js]

 [1js]: javascript:console.info("hello\ world");

 [2js]: hjavascript:console.info("hello\ world");

[Bookmarklet Attempt 2](javascript:console.info\("hello\ world"\);)
[Bookmarklet Hack 2](hjavascript:console.info\("hello\ world"\);)

**Comment by joemccann** [comment]
Likely has something to do with the Ace Editor.

**Comment by joemccann** [comment]
I can't reproduce this.
