### ISSUE TITLE
zen mode breaks preview mode

### ISSUE THREAD

**Issue by httpete-ire** [joemccann/dillinger#678]
Noticed a bug yesterday, when I open the zen mode while in the `html` preview mode it breaks the preview when zen mode is closed ([video of the bug](https://streamable.com/n3lgx)).

Quick fix would be to disable zen mode while in `html` preview mode

**Comment by joemccann** [comment]
Pull requests accepted!

**Comment by httpete-ire** [comment]
@joemccann yeah its still a bug. If I get time I'll have a look at a fix for it, my angular skills are a bit rusty 🤣
