### ISSUE TITLE
smart http link paste

### ISSUE THREAD

**Issue by niekobaarda** [joemccann/dillinger#679]
- smart http link paste:
[link](www.name.nl)
is relative
i.c. https://dillinger.io/www.name.nl
It should be absolute
i.c. http://www.name.nl
Thanks,
niekobaarda
Netherlands

**Comment by joemccann** [comment]
?

**Comment by niekobaarda** [comment]
Thanks for reply.

I can't reproduce the problem, sorry.


Greetings,
Nieko Baarda


⁣Sent from TypeApp ​
