### ISSUE TITLE
Cross Version Support (currently only Node v4.x.x according to `package.json`)

### ISSUE THREAD

**Issue by Ma27** [joemccann/dillinger#680]
Hi!

some time ago it has been attempted to create a package in the NixOS Linux distribution for `dillinger` (see NixOS/nixpkgs#32275). As of our latest release (18.03) we dropped support for NodeJS v4 as it's almost deprecated (https://github.com/nodejs/Release#release-schedule).
However this package requires NodeJS v4 (https://github.com/joemccann/dillinger/blob/ddd819031030388a44729b7a26a8107fa0762d8e/package.json#L41).

Before we actually merge this in our distro's package set it might be helpful to know if it's actually intended to run this with more recent NodeJS versions.

Thanks!

**Comment by joemccann** [comment]
This is fixed.
