### ISSUE TITLE
Dillinger web down?

### ISSUE THREAD

**Issue by alberduris** [joemccann/dillinger#682]
Hi,

I'm trying to access my documents but when I enter [Dillinger](https://dillinger.io/) the only thing I see is the logo.

![image](https://user-images.githubusercontent.com/7073086/39858779-de73388c-5437-11e8-9f77-87ac0590f810.png)

Is the service down or something?

Thanks.

**Comment by MathieuMorrissette** [comment]
same issue

**Comment by octipus** [comment]
same issue here

**Comment by morgyface** [comment]
Same.

**Comment by joemccann** [comment]
So weird. Nothing has changed whatsoever and there are no errors in the
console.  I'll try to figure out what's going on.

**Comment by morgyface** [comment]
Thanks Joe. Always seems well out of order _complaining_ about a free service. Especially when it's as good as Dillinger. Thank you for all your hard work.

**Comment by joemccann** [comment]
No problem!  I just don't understand happened!  Literally nothing has
changed in weeks and its been running on GCP for months now.

**Comment by joemccann** [comment]
Ok I found the issue but have no idea why it's happening.

If you know how to use Chrome Dev Tools, copy/paste in the following and hit enter:

```js
jQuery(".splashscreen").animate({opacity:0},150,function(){return jQuery(".splashscreen").remove()})
```

**Comment by joemccann** [comment]
I'm going to hunt down why this JS isn't being executed _all of the sudden_ -- very strange as nothing has changed.

**Comment by joemccann** [comment]
As expected, running locally with a fresh build shows no issues.  I've purged everything on Cloudflare as well...standby

**Comment by steveshelton** [comment]
You're serving malware / adware.  Just an FYI.
Starting on line 24 (from a view source of the website)
```

<script type="31933bf6c2cc064816e329f0-text/javascript">
var trackOutboundLink = function(url) {
 ga('send', 'event', 'outbound', 'click', url, {
  'transport': 'beacon',
  'hitCallback': function(){window.open(url);}
  });
  }
 </script>
```
Also starting on line 854
```

<script src="https://m.servedby-buysellads.com/monetization.js" type="31933bf6c2cc064816e329f0-text/javascript"></script>  
  <script type="31933bf6c2cc064816e329f0-">
  (function(){
  if(typeof _bsa !== 'undefined' && _bsa) {
  _bsa.init('default', 'CVADP53W', 'placement:dillingerio', {
  target: '.ad-container',
  align: 'horizontal',
  disable_css: 'true'
  });
  }
  })();
  </script>
```
If you look closely you'll see this code...
31933bf6c2cc064816e329f0

It's in several strange places
Are you infected somehow?

**Comment by steveshelton** [comment]
Actually that code changes on each page view...
```
5aa94e66b88df49639c26ab3
```

**Comment by steveshelton** [comment]
Think it's possible the problem is actually Cloudflare getting hijacked and injected?
It's happened before...
https://www.zdnet.com/article/aws-traffic-hijack-users-sent-to-phishing-site-in-two-hour-cryptocurrency-heist/

**Comment by joemccann** [comment]
Bingo. It's not me dude, I'm not serving malware.  

I serve ads to pay for the hosting for this *free* service, from BuySellAds which is a legit ad network.  Moreover, that outbound link tracker is for Google Analytics to track clicks of ads.  There's nothing nefarious here and if you don't like ads, use an Ad Blocker or Brave or simply, don't use Dillinger.io.

**Comment by joemccann** [comment]
This is a Cloudflare issue.

**Comment by joemccann** [comment]
@alberduris @MathieuMorrissette @octipus @morgyface 

This was a Cloudflare issue with Rocket Loader, which I have since disabled.  I've loaded it in Incognito in Chrome and Private Tab in Brave and it loads fine.  Please let me know if you are still having issues.

**Comment by joemccann** [comment]
Thanks @steveshelton!

Yes, Brendan Eich is actually a close friend of mine and I use Brave pretty much 95% of the time when I'm browsing the web.

I'll be joining that list of publishers.

**Comment by alberduris** [comment]
Wow @joemccann great work you did here today! 

Thank you very much for this project, for all your work, and specifically, for today's fix.

You're awesome! Keep up the good work! 💃 

Alber.

**Comment by joemccann** [comment]
🙏🏼
