### ISSUE TITLE
Fix elastic scroll / rubberband scrolling on #editor …

### ISSUE THREAD

**Issue by fooness** [joemccann/dillinger#685]
I tried to disable the weird elastic scroll / rubberband scrolling on #editor on iOS, but unfortunately without success. When visiting your dillinger with an iOS device, you can move the #editor up and down and you can see the sidebar behind this layer. Maybe you know any way to fix this.

**Comment by joemccann** [comment]
Not sure :/

**Comment by joemccann** [comment]
@fooness can you provide me with a screenshot?

**Comment by fooness** [comment]
@joemccann sure, here you go. The `#editor` div (I think) can be scrolled to the top so the *underlying* `Save Session` button is revealed.

![img_2469](https://user-images.githubusercontent.com/11408027/46671143-4ec77580-cbd4-11e8-8ede-439f3b7e5f65.PNG)
