### ISSUE TITLE
save failed to commit to github

### ISSUE THREAD

**Issue by marcoeg** [joemccann/dillinger#687]
The Javascript debugger console shows: 'Possibly unhandled rejection: cancel'.

**Comment by marcoeg** [comment]
Full message:

bundle.js:173 POST https://dillinger.io/save/github 502 ()
(anonymous) @ bundle.js:173
w @ bundle.js:173
c @ bundle.js:173
l @ bundle.js:174
(anonymous) @ bundle.js:174
$digest @ bundle.js:174
$apply @ bundle.js:174
(anonymous) @ bundle.js:176
dispatch @ bundle.js:25
g.handle @ bundle.js:24
bundle.js:174 TypeError: Cannot read property 'content' of undefined
    at Object.l [as updateSHAOnDocument] (bundle.js:222)
    at bundle.js:222
    at l (bundle.js:174)
    at bundle.js:174
    at p.$digest (bundle.js:174)
    at p.$apply (bundle.js:174)
    at a (bundle.js:173)
    at v (bundle.js:173)
    at XMLHttpRequest.w.onload (bundle.js:173) "Possibly unhandled rejection: {}"
(anonymous) @ bundle.js:174
(anonymous) @ bundle.js:173
c @ bundle.js:174
$digest @ bundle.js:174
$apply @ bundle.js:174
a @ bundle.js:173
v @ bundle.js:173
w.onload @ bundle.js:173
load (async)
(anonymous) @ bundle.js:173
w @ bundle.js:173
c @ bundle.js:173
l @ bundle.js:174
(anonymous) @ bundle.js:174
$digest @ bundle.js:174
$apply @ bundle.js:174
(anonymous) @ bundle.js:176
dispatch @ bundle.js:25
g.handle @ bundle.js:24

**Comment by joemccann** [comment]
Hmm strange...nothing has changed in months...ad blocker on?

**Comment by marcoeg** [comment]
It is even worse than originally reported. Upon reloading the file, it has wiped out the committed changes by committing unasked, a previous empty version. Will stop using it.
