### ISSUE TITLE
markdown source formatting

### ISSUE THREAD

**Issue by paulirish** [joemccann/dillinger#7]
Editing using Mou.app I get some pretty badass formatting of my markup...

![omg](http://paulirish.com/i/657c70.png)

I know we're using Ace editor here but I'm curious if anything similarly can be done. 

Also again, not your fault, but the markdown syntax highlighting in ace could use some improvement so headlines are a diff color than body text, etc.

:heart:

**Comment by vanceza** [comment]
This would be great to see cross-posted with https://github.com/ajaxorg/ace so you can get in dialog with Ace, and potentially improve markdown support for a wider range of Ace users, instead of just Dillinger.
