### ISSUE TITLE
Feature Request: Support for Table Formatting (as in GFM)

### ISSUE THREAD

**Issue by mstred** [joemccann/dillinger#70]
Hello,

I've found your app today and got very interested in that. But I think it is missing a cool feature which isn't a standard on Gruber's Markdown Syntax, but became very popular from the GitHub Flavored Markdown implementation: table formatting.

I tried to type this on [dillinger](http://dillinger.io):

```
  this  |  is  |  a   |  table  
--------|------|------|-----------
  with  | some | data |  on it
```

...and the text was showed just like that. As you can see below (and as this text is formatted with GFM), the same content is rendered right here:

| this | is | a | table |
| --- | --- | --- | --- |
| with | some | data | on it |

**Comment by Dangthrimble** [comment]
Though the table feature works, there are no borders around the cells which makes it appear less of a table.

```
Column 1 | column 2
-|
First row | Fred
Second row | Freda
```

is rendered as

![dillinger table](https://cloud.githubusercontent.com/assets/1872986/6619243/ef5bc3e0-c8c0-11e4-8082-af94a9a44307.png)

**Comment by joemccann** [comment]
Probably just need to change the CSS of dillinger then...have a go!

**Comment by nmondal** [comment]
This baffled me --- facing this issue, what I need to do ?

**Comment by joemccann** [comment]
I would check the `.scss` files for `table` and its respective properties.  Then, rebuild the css

**Comment by WebDragon** [comment]
Pandoc also has extended the available markdown options for tables in a useful way, that we currently use to maintain the wine-list on the website of one of our clients :

```
Table: Magnum

------------------------------------------------------------------------------------------
Bin #  Wine                                                                Glass   Bottle
------ ------------------------------------------------------------------ ------- --------
197     Brandlin Estate Grown Cabernet Sauvignon, Mount Veeder,
        Napa, CA 2011                                                               97.00

198     Hartford Court Russian River Valley Chardonnay, Sonoma, CA 2014             49.00

199     Bouchaine Estate Chardonnay, Careneros, Napa, CA 2014                       69.00

------------------------------------------------------------------------------------------
```
which results in: 
<table class="table table-striped table-hover table-sm">
<caption>Magnum</caption>
<colgroup>
<col style="width: 7%" />
<col style="width: 74%" />
<col style="width: 8%" />
<col style="width: 8%" />
</colgroup>
<thead>
<tr class="header">
<th >Bin #</th>
<th >Wine</th>
<th >Glass</th>
<th >Bottle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td >197</td>
<td >Brandlin Estate Grown Cabernet Sauvignon, Mount Veeder, Napa, CA 2011</td>
<td ></td>
<td >97.00</td>
</tr>
<tr class="even">
<td >198</td>
<td >Hartford Court Russian River Valley Chardonnay, Sonoma, CA 2014</td>
<td ></td>
<td >49.00</td>
</tr>
<tr class="odd">
<td >199</td>
<td >Bouchaine Estate Chardonnay, Careneros, Napa, CA 2014</td>
<td ></td>
<td >69.00</td>
</tr>
</tbody>
</table>

Makes for a very easy to read (and more importantly easy to edit!) document without all the inter-lines between cells, and all you need to do is mind your spacing. 

if you could somehow enable this format as well, that would be fantastic.

**Comment by WebDragon** [comment]
does your setup allow for the use or the implementation of extensions on top or instead of things? Pandoc itself has multiple extensions both enabled and disabled by default in its flavor .. and according to their manpage {also ref: [Pandoc Issue 2256](https://github.com/jgm/pandoc/issues/2256) }, you can choose to switch to MultiMarkdown, PHP Markdown Extra, GFM, or Markdown Strict, thus limiting it to not include the pandoc extras. 

Though I don't offhand know how, I'm certain that if your setup at least supports extending beyond the basic GFM, that it would be possible to say, cull the pandoc table extensions out as an extension, if you didn't just want to use pandoc itself in the first place, since it already has support for GFM built in. :D
