### ISSUE TITLE
"Preview as" gives "Internal Server Error"

### ISSUE THREAD

**Issue by AlexWayfer** [joemccann/dillinger#701]
Hello!

"Preview as" with any content and any format open a new tab with "Internal Server Error".

Thanks.

**Comment by joemccann** [comment]
Not seeing this bug.

![dill](https://user-images.githubusercontent.com/48234/49512898-9b0afb00-f88f-11e8-86ab-db6a3a7cfe16.gif)

**Comment by AlexWayfer** [comment]
I'm sorry, not any content. It should be triggered the first time with specific content for following errors with any content.

There is content:

```
# Обновление 4 декабря 2018
```

It seems that this should be copy-pasted, not re-typed.

Also, it'd be nice to check errors (logs) on server for reports about server errors.

**Comment by AlexWayfer** [comment]
OK, I'm sorry for my English.

Steps to reproduce:

1. Open Dillinger
2. Remove default content
3. Paste `# Обновление 4 декабря 2018`
4. Press "Preview as" → "HTML"

![peek 2018-12-05 19-03](https://user-images.githubusercontent.com/6510020/49526215-6b281b80-f8c0-11e8-998c-0e6d0aae54c3.gif)

> Also, it'd be nice to check errors (logs) on server for reports about server errors.

I think, you should check server logs when somebody reports about server errors.
