### ISSUE TITLE
Node Deprecated Packages 

### ISSUE THREAD

**Issue by ClickSentinel** [joemccann/dillinger#715]
Is this application still be supported and updated? There are many deprecated and unsupported packages held in `node`.

|  Package | Current | Wanted | Latest | Location |
| ------- | ------- | ------- | ------- | ------- |
| babel-loader | 7.1.5 | 7.1.5 | 8.0.5 | Dillinger |
| balanced-match | 0.2.1 | 0.2.1 | 1.0.0 | Dillinger |
| breakdance | 0.1.7 | 0.1.7 | 3.0.1 | Dillinger |
| clean-css | 3.4.28 | 3.4.28 | 4.2.1 | Dillinger |
| connect-assets | 5.4.0 | 5.4.0 | 6.0.0 | Dillinger |
| critical | 0.6.0 | 0.6.0 | 1.3.4 | Dillinger |
| css-loader | 0.9.1 | 0.9.1 | 2.1.1 | Dillinger |
| debug | 2.6.9 | 2.6.9 | 4.1.1 | Dillinger |
| depd | 1.1.2 | 1.1.2 | 2.0.0 | Dillinger |
| dropbox | 3.0.5 | 3.0.5 | 4.0.17 | Dillinger |
| es6-promise | 3.3.1 | 3.3.1 | 4.2.6 | Dillinger |
| exports-loader | 0.6.4 | 0.6.4 | 0.7.0 | Dillinger |
| glob | 5.0.15 | 5.0.15 | 7.1.3 | Dillinger |
| googleapis | 2.1.7 | 2.1.7 | 39.1.0 | Dillinger |
| gulp | 3.9.1 | 3.9.1 | 4.0.0 | Dillinger |
| gulp-autoprefixer | 3.1.1 | 3.1.1 | 6.0.0 | Dillinger |
| gulp-csso | 0.2.9 | 0.2.9 | 3.0.1 | Dillinger |
| gulp-if | 2.0.0 | 2.0.0 | 2.0.2 | Dillinger |
| gulp-notify | 2.2.0 | 2.2.0 | 3.2.0 | Dillinger |
| gulp-open | 0.3.2 | 0.3.2 | 3.0.1 | Dillinger |
| gulp-rev | 8.1.1 | 8.1.1 | 9.0.0 | Dillinger |
| gulp-rimraf | 0.2.0 | 0.2.0 | 0.2.2 | Dillinger |
| gulp-sass | 2.3.2 | 2.3.2 | 4.0.2 | Dillinger |
| gulp-size | 1.3.0 | 1.3.0 | 3.0.0 | Dillinger |
| gulp-tar | 1.9.0 | 1.9.0 | 2.1.0 | Dillinger |
| gulp-zip | 3.2.0 | 3.2.0 | 4.2.0 | Dillinger |
| hard-source-webpack-plugin | 0.12.0 | 0.12.0 | 0.13.1 | Dillinger |
| highlight.js | 8.9.1 | 8.9.1 | 9.15.6 | Dillinger |
| inverseresize | 1.0.0 | git | git | Dillinger |
| jasmine-core | 2.99.1 | 2.99.1 | 3.3.0 | Dillinger |
| jquery-ui-bundle | 1.12.1 | 1.12.1 | 1.12.1 | migrate  Dillinger |
| jshint-stylish | 1.0.2 | 1.0.2 | 2.2.1 | Dillinger |
| karma | 1.7.1 | 1.7.1 | 4.0.1 | Dillinger |
| karma-chrome-launcher | 0.1.12 | 0.1.12 | 2.2.0 | Dillinger |
| karma-cli | 1.0.1 | 1.0.1 | 2.0.0 | Dillinger |
| karma-jasmine | 1.1.2 | 1.1.2 | 2.0.1 | Dillinger |
| karma-webpack | 1.8.1 | 1.8.1 | 3.0.5 | Dillinger |
| katex | 0.9.0 | 0.9.0 | 0.10.1 | Dillinger |
| markdown-it | 4.4.0 | 4.4.0 | 8.4.2 | Dillinger |
| markdown-it-deflist | 1.0.0 | 1.0.0 | 2.0.3 | Dillinger |
| markdown-it-footnote | 1.0.0 | 1.0.0 | 3.0.1 | Dillinger |
| markdown-it-ins | 1.0.0 | 1.0.0 | 2.0.0 | Dillinger |
| markdown-it-mark | 1.0.0 | 1.0.0 | 2.0.0 | Dillinger |
| markdown-it-math | 3.0.2 | 3.0.2 | 4.1.1 | Dillinger |
| memory-fs | 0.2.0 | 0.2.0 | 0.4.1 | Dillinger |
| method-override | 2.3.10 | 2.3.10 | 3.0.0 | Dillinger |
| ng-annotate-webpack-plugin | 0.1.3 | 0.1.3 | 0.3.0 | Dillinger |
| node-sass | 3.13.1 | 3.13.1 | 4.11.0 | Dillinger |
| parse-link-header | 0.4.1 | 0.4.1 | 1.0.1 | Dillinger |
| pretty-hrtime | 0.2.2 | 0.2.2 | 1.0.3 | Dillinger |
| raw-loader | 0.5.1 | 0.5.1 | 2.0.0 | Dillinger |
| rc | 0.3.0 | 0.3.0 | 1.2.8 | Dillinger |
| reaver | 1.2.0 | 1.2.0 | 2.0.0 | Dillinger |
| run-sequence | 1.2.2 | 1.2.2 | 2.2.1 | Dillinger |
| style-loader | 0.8.3 | 0.8.3 | 0.23.1 | Dillinger |
| temp | 0.8.3 | 0.8.3 | 0.9.0 | Dillinger |
| walkdir | 0.0.11 | 0.3.2 | 0.3.2 | Dillinger |
| webpack-dev-server | 1.16.5 | 1.16.5 | 3.2.1 | Dillinger |
| yargs | 1.3.3 | 1.3.3 | 13.2.2 | Dillinger |

**Comment by joemccann** [comment]
Pull requests accepted!

**Comment by ClickSentinel** [comment]
Excellent. I will update and configure the application to work with updated node packages and submit a pull request. Thank you.

**Comment by joemccann** [comment]
Did you submit a PR?

**Comment by ClickSentinel** [comment]
I'll be honest... I couldn't fix it at that time. I may revisit this soon. Feel free to close this ticket. 

Sorry about that.
