### ISSUE TITLE
Considered making dillinger an npm package

### ISSUE THREAD

**Issue by theghostyced** [joemccann/dillinger#724]
Hi @joemccann. I absolutely love this platform and wanted to push this idea to you.

Blogging is everything these days and with platforms like `dev.to`, `scotch.io` that use markdown format to write an article having a package like dillinger that provides the markdown editor would be amazing IMO.

Just a thought though

**Comment by joemccann** [comment]
Take a stab at it!

**Comment by joemccann** [comment]
@theghostyced interest in submitting a PR?

**Comment by theghostyced** [comment]
I would have honestly loved to @joemccann but currently am choked with other engagements. But if you do decide to do let me know 🙏

**Comment by edogbosunny** [comment]
Hey @theghostyced I would like to join you on this if that's ok. this would be fun

**Comment by joemccann** [comment]
@edogbosunny have at it!
