### ISSUE TITLE
resize image

### ISSUE THREAD

**Issue by siddbudd** [joemccann/dillinger#725]
I am not able to resize images using either of the following methods:

```
![alt](image.jpg){ width=20% }
<img src="image.jpg" alt="alt" width="200"/>
```

do you have a working solution?

**Comment by joemccann** [comment]
Not sure this is possible

**Comment by siddbudd** [comment]
Thanks for the quick reply. Would you potentially consider implementing html support in future so that images can be resized? Most desktop markdown programs support that, but they generally don't use as nice style sheets as you do. Especially those checkboxes for `[ ]` are just wonderful :D

**Comment by joemccann** [comment]
Dillinger uses Ace editor. If Ace supports it we can do it!

**Comment by siddbudd** [comment]
You mean Ace editor generates and renders the html code as well?

**Comment by joemccann** [comment]
correct
