### ISSUE TITLE
Maintain link to services between sessions

### ISSUE THREAD

**Issue by schultzter** [joemccann/dillinger#732]
Is it normal to loose my links to services, such as Google Drive and Dropbox, between sessions? 

I would like the links to persist so I don't have to re-authorize every time. 

Thanks.

**Comment by joemccann** [comment]
Hmm that shouldn't happen.

**Comment by schultzter** [comment]
So obviously I can't reproduce the problem now that I've created an issue for it!

What happens now is when I open my browser and then open dillinger.io none of the services are linked. But when I click on one that I've previously linked (like Google Drive) dillinger.io reloads with the link activated. 

Is that normal?

**Comment by schultzter** [comment]
Ah, ok. I've figured it out.

I normally log out of Dropbox when I'm done, and I don't use the web portal that often. So when I try to Import a file from Dropbox then I guess dillinger needs me to login to Dropbox first (which dillinger kicks off using the authorization flow). 

GDrive works more reliably since I'm usually logged in to GMail already when I open dillinger. So dillinger just has to reload with the GDrive link activated, no need for me to login & authorize. 

But because of issue #238 I've been trying dillinger with Dropbox, so that's why I was noticing this problem more. 

Thanks

**Comment by joemccann** [comment]
You should connect to a service once and it stays linked.

The only thing I can think of is the way Zeit's now does hosting and how
sessions are handled.

Dillinger is hosted on Zeit's Now.
