### ISSUE TITLE
Should reduce reliance on third-party files.

### ISSUE THREAD

**Issue by XianwuLin** [joemccann/dillinger#736]
When I was using the environment built by docker, I found that some js files and css files in the page are not used by 127.0.0.1, but are similar like:
* https://m.servedby-buysellads.com/monetization.js
* https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700
* https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.css
* https://fonts.gstatic.com/s/ubuntumono/v9/KFO-CneDtsqEr0keqCMhbC-BL9H1tY0.woff2
...

Can you reduce the dependencies of these third-party files?

**Comment by joemccann** [comment]
Pull requests accepted!

**Comment by joemccann** [comment]
@XianwuLin are you looking to submit a PR?

**Comment by joemccann** [comment]
Closing
