### ISSUE TITLE
Anchor Can't use?

### ISSUE THREAD

**Issue by dbwodlf3** [joemccann/dillinger#740]
i read https://www.markdownguide.org/extended-syntax/#heading-ids

In dillinger editor, i would like to make anchor link but, i can't add name or id for a target.

there is anything to use anchor?

**Comment by joemccann** [comment]
It may be an issue with Ace Editor

**Comment by dbwodlf3** [comment]
i mean, how to make custom id or name attribute for anchor? it is impossible?

**Comment by joemccann** [comment]
Right have a look at the ace editor docs
