### ISSUE TITLE
issue with github Integration

### ISSUE THREAD

**Issue by Rajpratik71** [joemccann/dillinger#743]
Hi , 

Currently , having issue with github integration in any form like : 

1 . In Services Section link with github not working

2. Save to and Import from github feature is also not working

On request gives "getaddrinfo EAI_AGAIN github.com" error on request page . 

On some research found the error is related to "DNS lookup timed out error, means it is a network connectivity error or proxy related error."

**Comment by joemccann** [comment]
Hmm odd. Dillinger is running on Zeit. Any network issues?

**Comment by Rajpratik71** [comment]
Here , the issue is doesn't with the Zeit (hosting) , this is the issue with Github api integration . 

you should contact [Github Support](https://support.github.com/contact)  if unresolvable.

**Comment by joemccann** [comment]
Oh sorry, I misread that.

Did GitHub change the API? This code has worked for 8 years without any
issues.

**Comment by joemccann** [comment]
This appears to be a known issue on Zeit:

https://spectrum.chat/zeit/now/dns-error-error-getaddrinfo-eai-again~5ea9f263-bded-479f-9e22-23c98effef87

**Comment by joemccann** [comment]
I just received this email from GitHub:

```On February 3rd, 2020 at 22:53 (UTC) your application (Dillinger) used an access token (with the User-Agent X-Dillinger-App) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team```

**Comment by Rajpratik71** [comment]
yes , that what i was told u about , that it is github api integration issue . This occurred due to change in the api , u should update the api integration codes according to need.

**Comment by joemccann** [comment]
Pull Requests welcome.  I'll try to get to in within the coming months

**Comment by joemccann** [comment]
This should be fixed now that I'm running this on Azure in a VM.
