### ISSUE TITLE
Export stopped working

### ISSUE THREAD

**Issue by lakesare** [joemccann/dillinger#744]
When I click 'Export as -> Pdf', I get redirected to https://dillinger.io/factory/fetch_pdf, and shown a message:

```
Failed to launch chrome!
/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

**Comment by joemccann** [comment]
Yeah this is a known issue.  Puppeteer can't run properly or Lambda or
really any cloud provider without a bunch of surgery.  I'm open to pull
requests.

**Comment by lakesare** [comment]
Wasn't it working very recently?

**Comment by joemccann** [comment]
PDF broke a couple months ago as the version of Node.js on Zeit was
upgraded and no longer supported the version of PhantomJS

**Comment by planetahuevo** [comment]
I am having this issue.
Would be possible to remove the "export button" with a config?
Another option is to remove the error and redirect to an error page? 

Thanks
