### ISSUE TITLE
reset profile does not work for me

### ISSUE THREAD

**Issue by johnoo** [joemccann/dillinger#747]
I use Waterfox 2020.02.1
I delete all saved documents, reset profile, even save session after reset. Then I close tab, Open new tab, reach dillinger.io - everything as expected - last save after reset. Then I close browser - I have setting to delete cookies. I open browser (i have setting to remember last open tabs) with Dillinger opened already and it reopens old documents. 
I have multiple portable browsers  - 
1. this my general use waterfox
2. older copy of previous one used for different purpose - saved in different folder (different name of the folder)
3. one new Firefox and one iron browser

in Firefox and Iron it does not happen but interesting is that if I open dillinger in the second browser (browser 2) dillinger reopens documents. 
I never saved documents from browser to any cloud or to pc (just copy and paste text / html).
To me it looks like dillinger saves documents offline to pc with autosave and it does not delete them when reset profile or delete document. ...
I deleted history and bookmark entries of dillinger, cache in my browser 
I can make a video about it. I use Dillinger.io not local deployment

**Comment by joemccann** [comment]
It's because the `localStorage` for the current tab, not systemwide.  `localStorage` doesn't sync across browser tabs.
