### ISSUE TITLE
Add local images

### ISSUE THREAD

**Issue by giovannirescia** [joemccann/dillinger#770]
I am running the app locally, but I can't manage to add some local images to the document, I have something like:

`![img1](/home/user/images/img1.png)`

But it doesn't work. I also couldn't find where the documents are stored when running the app.

Thanks,
Giovanni

**Comment by joemccann** [comment]
Dillinger only supports images when your Dropbox is connected since
Dillinger.io doesn't host images (too expensive).

**Comment by giovannirescia** [comment]
Somehow I thought that running Dillinger locally would allow to include local paths.
Thanks!
