### ISSUE TITLE
Some unicode characters mess up text cursor

### ISSUE THREAD

**Issue by Devaniti** [joemccann/dillinger#818]
Using this characters `↑←↓→` mess up position of text cursor in edit field (haven't tested all unicode characters, more characters may trigger same bug)
Cursor visual position doesn't match up with real cursor position
e.g. for line `↑←↓→ - Some Text` if cursor is visually after `→` character in reality typing will result in characters appearing after `-` character

**Comment by joemccann** [comment]
This is an Ace Editor issue, which Dillinger depends on.
