### ISSUE TITLE
Open a URL?

### ISSUE THREAD

**Issue by danielshahaf** [joemccann/dillinger#833]
If I have a URL to a markdown file, can I have dillinger open that file?  Ideally, by passing the URL to dillinger in the URL (i.e., `https://dillinger.io.example/?url=https://foo.example.com/bar.md`)?  The file isn't in github/dropbox/*; it's just a random HTTP GET-able file.

Sorry if this is documented elsewhere, but I couldn't find the answer in the docs / issues / [searching](https://stackoverflow.com/questions/16461310/how-to-view-an-online-markdown-document-in-an-online-editor) (by the way, neither of the alternatives in that stackoverflow post works now).

**Comment by joemccann** [comment]
We don't support this functionality

**Comment by danielshahaf** [comment]
Thanks for the answer.  You might want to view this as a feature request.  My use-case for this was that I wanted to link someone to an HTML-rendered version of markdown documentation from the latest commit in a random branch (i.e., documentation of tip of master, rather than of the latest release).  Cheers!
