### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by freebeans** [joemccann/dillinger#864]
Hey, [dillinger.io](https://dillinger.io/) seems to be down.
It was working some hours ago.

![Captura de tela de 2024-05-09 17-08-54](https://github.com/joemccann/dillinger/assets/16484695/11b51097-5ceb-457a-a2a4-cb0175b3c272)

![Captura de tela de 2024-05-09 17-09-40](https://github.com/joemccann/dillinger/assets/16484695/20df81a5-5abf-45b2-b3e2-16e42c9f7f18)

**Comment by geoidesic** [comment]
It's working again
