### ISSUE TITLE
marked parser and mathjax support

### ISSUE THREAD

**Issue by sgon00** [joemccann/dillinger#93]
Hi, today when I search markdown editors, I found a few, but this one has the best UI interface. Everything is perfect except the markdown parser and no mathjax support. 

1, why don't use marked parser instead of Showdown? 

I tried EpicEditor which uses marked parser. I feel it's much better than showdown. For instance, *\* bold fonts *\* can be parsered correctly in marked. but it will not work here. I have to remove the spaces **bold fonts** for Showdown.

2, any plan for mathjax support? 

I need to input math formula. but it's not supported here.
http://jaxedit.com/mark/ is a project which combines both markdown and mathjax.

Thanks a lot.

**Comment by vlad17** [comment]
@joemccann Would you mind answering the second question?

**Comment by joemccann** [comment]
Mathjax support is also something that could easily be added...give it a go! @vlad17

**Comment by vlad17** [comment]
I'd love to but I'm afraid I don't have the right experience for that job!
